/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2017-08-26 04:38:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class account_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\"> \n");
      out.write("<title>new account</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<!-- <form action = \"/mainpage/process.jsp\" method = \"POST\" > -->\n");
      out.write("\t\t<div class= \"account\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<form action = \"/mainpage/a1.jsp\" method = \"POST\" >\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t<div class = \"goMainPage\">\n");
      out.write("\t\t\t\t\t\t<button class = \"AaveButton\" > go to welcome page </button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<form action = \"/mainpage/show_info.jsp\" method = \"POST\" >\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t<div class = \"goFruitMenu\">\n");
      out.write("\t\t\t\t\t\t<button class = \"AaveButton\" > go to fruit menu </button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</form>\n");
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t<form action = \"/mainpage/process.jsp\" method = \"POST\" >\n");
      out.write("\t\t\t<h3 class = \"title_account\"> Hi, dear our new customer, please provide your information to us </h3> <br>\n");
      out.write("\t\t\t\t<div class = \"accountBox\">\n");
      out.write("\t\t\t \tFirst name: <input class = \"fistAccount\" type=\"text\" name=\"fname\"><br>\n");
      out.write("\t\t\t \t<br>\n");
      out.write("\t\t\t\tLast name: <input class = \"lastAccount\"  type=\"text\" name=\"lname\"><br>\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t\tPassword: <input class = \"passwoardAccount\"  type = \"password\" name= \"password\" placeholder=\"At least 8 digits\"> <span class =\"rem_word\"  >  </span> <br>\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t\tEmail: <input class = \"emailAccount\" type=\"text\" name=\"email\"><br>\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t\tMobile number: <input class = \"mobileAccount\"  type=\"text\" name=\"mobno\" placeholder=\"Digits only \"> <span class =\"rem_word\"> </span>  <br>\t\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Address: <textarea rows=\"5\" cols=\"5\" name=\"address\"></textarea><br> -->\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t\tAddress: <input class = \"addressAccount\"  type=\"text\" name=\"address\"> \n");
      out.write("\t\t\t\tCity: <input  class = \"cityAccount\" type=\"text\" name=\"city\"> <br>\n");
      out.write("\t\t\t\tState: <select class = \"stateAccount\" name=\"state\" size=\"1\">\n");
      out.write("\t\t\t\t<option selected value=\"\">State...</option>\n");
      out.write("\t\t\t\t<option value=\"Alabama\">Alabama</option>\n");
      out.write("\t\t\t\t<option value=\"Alaska\">Alaska</option>\n");
      out.write("\t\t\t\t<option value=\"Arizona\">Arizona</option>\n");
      out.write("\t\t\t\t<option value=\"Arkansas\">Arkansas</option>\n");
      out.write("\t\t\t\t<option value=\"California\">California</option>\n");
      out.write("\t\t\t\t<option value=\"Colorado\">Colorado</option>\n");
      out.write("\t\t\t\t<option value=\"Connecticut\">Connecticut</option>\n");
      out.write("\t\t\t\t<option value=\"Delaware\">Delaware</option>\n");
      out.write("\t\t\t\t<option value=\"Florida\">Florida</option>\n");
      out.write("\t\t\t\t<option value=\"Georgia\">Georgia</option>\n");
      out.write("\t\t\t\t<option value=\"Hawaii\">Hawaii</option>\n");
      out.write("\t\t\t\t<option value=\"Idaho\">Idaho</option>\n");
      out.write("\t\t\t\t<option value=\"Illinois\">Illinois</option>\n");
      out.write("\t\t\t\t<option value=\"Indiana\">Indiana</option>\n");
      out.write("\t\t\t\t<option value=\"Iowa\">Iowa</option>\n");
      out.write("\t\t\t\t<option value=\"Kansas\">Kansas</option>\n");
      out.write("\t\t\t\t<option value=\"Kentucky\">Kentucky</option>\n");
      out.write("\t\t\t\t<option value=\"Louisiana\">Louisiana</option>\n");
      out.write("\t\t\t\t<option value=\"Maine\">Maine</option>\n");
      out.write("\t\t\t\t<option value=\"Maryland\">Maryland</option>\n");
      out.write("\t\t\t\t<option value=\"Massachusetts\">Massachusetts</option>\n");
      out.write("\t\t\t\t<option value=\"Michigan\">Michigan</option>\n");
      out.write("\t\t\t\t<option value=\"Minnesota\">Minnesota</option>\n");
      out.write("\t\t\t\t<option value=\"Mississippi\">Mississippi</option>\n");
      out.write("\t\t\t\t<option value=\"Missouri\">Missoquri</option>\n");
      out.write("\t\t\t\t<option value=\"Montana\">Montana</option>\n");
      out.write("\t\t\t\t<option value=\"Nebraska\">Nebraska</option>\n");
      out.write("\t\t\t\t<option value=\"Nevada\">Nevada</option>\n");
      out.write("\t\t\t\t<option value=\"New Hampshire\">New Hampshire</option>\n");
      out.write("\t\t\t\t<option value=\"New Jersey\">New Jersey</option>\n");
      out.write("\t\t\t\t<option value=\"New Mexico\">New Mexico</option>\n");
      out.write("\t\t\t\t<option value=\"New York\">New York</option>\n");
      out.write("\t\t\t\t<option value=\"North Carolina\">North Carolina</option>\n");
      out.write("\t\t\t\t<option value=\"North Dakota\">North Dakota</option>\n");
      out.write("\t\t\t\t<option value=\"Ohio\">Ohio</option>\n");
      out.write("\t\t\t\t<option value=\"Oklahoma\">Oklahoma</option>\n");
      out.write("\t\t\t\t<option value=\"Oregon\">Oregon</option>\n");
      out.write("\t\t\t\t<option value=\"Pennsylvania\">Pennsylvania</option>\n");
      out.write("\t\t\t\t<option value=\"Rhode Island\">Rhode Island</option>\n");
      out.write("\t\t\t\t<option value=\"South Carolina\">South Carolina</option>\n");
      out.write("\t\t\t\t<option value=\"South Dakota\">South Dakota</option>\n");
      out.write("\t\t\t\t<option value=\"Tennessee\">Tennessee</option>\n");
      out.write("\t\t\t\t<option value=\"Texas\">Texas</option>\n");
      out.write("\t\t\t\t<option value=\"Utah\">Utah</option>\n");
      out.write("\t\t\t\t<option value=\"Vermont\">Vermont</option>\n");
      out.write("\t\t\t\t<option value=\"Virginia\">Virginia</option>\n");
      out.write("\t\t\t\t<option value=\"Washington\">Washington</option>\n");
      out.write("\t\t\t\t<option value=\"West Virginia\">West Virginia</option>\n");
      out.write("\t\t\t\t<option value=\"Wisconsin\">Wisconsin</option>\n");
      out.write("\t\t\t\t<option value=\"Wyoming\">Wyoming</option>\n");
      out.write("\n");
      out.write("\t\t\t\t</select>\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t<input class = \"EditButton\" type = \"submit\" value = \"create a new account\" name =\"submit\"  /> \n");
      out.write("\t\t\t\t<!-- <input type = \"submit\" value = \"show databases\" name =\"show databases\"  />  -->\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t</div>\n");
      out.write("\t\n");
      out.write("\t</form>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
