/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2017-11-20 08:01:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.File;
import java.io.Writer;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.util.Iterator;

public final class checkout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

 
			
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"mainfruit.css\"> \n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("\t\t\t<script> \n");
      out.write("\t\t\t$(document).ready(function(){\n");
      out.write("\t\t\t    $(\"#menu\").click(function(){\n");
      out.write("\t\t\t       /*  $(\"#panel\").toggle(10);  */\n");
      out.write("\t\t\t\t\t$(\".transparency\").toggle(10);  \n");
      out.write("\t\t\t        $(\".transparencyAccount\").toggle(20);\n");
      out.write("\t\t\t        $(\".transparencyWelcome\").toggle(30); \n");
      out.write("\t\t\t    });\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t</script>\n");
      out.write("<title>check out</title>\n");
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\t\t\tfunction myFunction() {\n");
      out.write("\n");
      out.write("\t\t\t\t\t\tvar myDiv = document.getElementById(\"myDiv\");\n");
      out.write("\t\t\t\t\t\t//Create array of options to be added\n");
      out.write("\t\t\t\t\t\tvar array = [\"Volvo\",\"Saab\",\"Mercades\",\"Audi\"];\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t//Create and append select list\n");
      out.write("\t\t\t\t\t\tvar selectList = document.createElement(\"select\");\n");
      out.write("\t\t\t\t\t\tselectList.setAttribute(\"id\", \"mySelect\");\n");
      out.write("\t\t\t\t\t\tmyDiv.appendChild(selectList);\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t//Create and append the options\n");
      out.write("\t\t\t\t\t\tfor (var i = 0; i < array.length; i++) {\n");
      out.write("\t\t\t\t\t\t    var option = document.createElement(\"option\");\n");
      out.write("\t\t\t\t\t\t    option.setAttribute(\"value\", array[i]);\n");
      out.write("\t\t\t\t\t\t    option.text = array[i];\n");
      out.write("\t\t\t\t\t\t    selectList.appendChild(option);\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t/* return   selectList.appendChild(option); */\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t}\t\t\t\t\n");
      out.write("\t\t\t</script>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<script type=\"text/javascript\">\n");
      out.write("\t \n");
      out.write("\t\t\tfunction itemnode2(a,b,c,d,e,topa ,myS, mydemo, newdiv, myButton, udateQ){\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tvar my_form=document.createElement('FORM');\n");
      out.write("\t\t\t\tmy_form.name='myForm';\n");
      out.write("\t \t\t\tmy_form.method='GET'; \n");
      out.write("\t\t\t\tmy_form.action='checkout.jsp'; \n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\tvar myDiv = document.createElement(\"DIV\");\n");
      out.write("\t\t\t\tmyDiv.setAttribute(\"id\", newdiv);\n");
      out.write("\t\t\t\tmyDiv.setAttribute(\"value\", newdiv);\n");
      out.write("\t\t\t\tmyDiv.style.position = 'absolute';\n");
      out.write("\t\t\t\t/* myDiv.style.width = '800px';\n");
      out.write("\t\t\t\tmyDiv.style.height = '200px'; */\n");
      out.write("\t\t\t\tmyDiv.style.width = '700px';\n");
      out.write("\t\t\t\tmyDiv.style.height = '150px';\n");
      out.write("\t\t\t\tmyDiv.style.top = topa;\n");
      out.write("\t\t\t\tmyDiv.style.left = '273px';\n");
      out.write("\t\t\t\t/* myDiv.style.background  = 'white'; */\n");
      out.write("\t\t\t\tmyDiv.style.backgroundColor = \"rgba(252, 252, 252 ,10)\";\n");
      out.write("\t\t\t\t/* background-color: rgba(211, 209, 209, 0.5); */\n");
      out.write("\t\t\t\tmy_form.appendChild(myDiv); \n");
      out.write("\t\t\t\t/* myDiv.style.background.opacity= '0.5'; */\n");
      out.write("\t\n");
      out.write("\t\t\n");
      out.write("\t\t\t    var image = document.createElement('img');\n");
      out.write("\t\t\t    image.src = b;   \n");
      out.write("\t\t\t    image.style.width = '20%'; \n");
      out.write("\t\t\t    image.style.position='absolute';\n");
      out.write("\t\t\t    image.style.left = '20px';\n");
      out.write("\t\t\t    image.style.top = '30px';\n");
      out.write("\t\t\t    myDiv.appendChild(image); \n");
      out.write("\t\t\t    my_form.appendChild(myDiv); \n");
      out.write("\t\t\t    \n");
      out.write("\t\t\t    var fruitname = document.createElement('P');\n");
      out.write("\t\t\t    fruitname.style.position='absolute';\n");
      out.write("\t\t\t    fruitname.style.left = '200px';\n");
      out.write("\t\t\t    fruitname.style.top = '40px';\n");
      out.write("\t\t\t    fruitname.style.fontSize = \"110%\";\n");
      out.write("\t\t\t    fruitname.style.fontFamily  = \"Lucida Sans Unicode,Lucida Grande,sans-serif\"; \n");
      out.write("\t\t\t    var word = document.createTextNode(a); \t\t\t \t\n");
      out.write("\t\t\t    fruitname.appendChild(word);\t\t\t   \n");
      out.write("\t\t\t    myDiv.appendChild(fruitname);\n");
      out.write("\t\t\t    my_form.appendChild(myDiv); \n");
      out.write("\t\t\t    \t\t\t    \n");
      out.write("\t\t\t    var price = document.createElement('P');\n");
      out.write("\t\t\t    price.style.position='absolute';\n");
      out.write("\t\t\t    price.style.left = '350px';\n");
      out.write("\t\t\t    price.style.top = '50px';\n");
      out.write("\t\t\t    var word = document.createTextNode(c); \t\t\t \t\n");
      out.write("\t\t\t    price.appendChild(word);\t\t\t   \n");
      out.write("\t\t\t    myDiv.appendChild(price);\n");
      out.write("\t\t\t    my_form.appendChild(myDiv); \n");
      out.write("\t\t\t    \n");
      out.write("\t\t\t    \n");
      out.write("\t\t\t    var selectq = document.createElement('select');\n");
      out.write("\t\t\t    selectq.style.position='absolute';\n");
      out.write("\t\t\t    selectq.style.left = '450px';\n");
      out.write("\t\t\t    selectq.style.top = '65px';\n");
      out.write("\t\t\t    selectq.setAttribute(\"id\", myS);\n");
      out.write("\t\t\t    selectq.setAttribute('name', myS);\n");
      out.write("\t\t\t\tmyDiv.appendChild(selectq);\t\n");
      out.write("\t\t\t\tmy_form.appendChild(myDiv); \t\t\n");
      out.write("\t\t\t\t//Create and append the options\n");
      out.write("\t\t\t\tvar array = [\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\"];\n");
      out.write("\t\t\t\tfor (var i = 0; i < array.length; i++) {\n");
      out.write("\t\t\t\t    var option = document.createElement(\"option\");\n");
      out.write("\t\t\t\t    option.setAttribute(\"value\", array[i]);\n");
      out.write("\t \t\t\t    if(array[i] == d ){\n");
      out.write("\t\t\t\t    \toption.setAttribute(\"selected\", \"selected\");\t\t\t\t    \t\n");
      out.write("\t\t\t\t    } \n");
      out.write("\t\t\t\t    \n");
      out.write("\t\t\t\t    option.text = array[i];\n");
      out.write("\t\t\t\t    selectq.appendChild(option);\n");
      out.write("\t\t\t\t}\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tvar totalprice = document.createElement('P');\n");
      out.write("\t\t\t\ttotalprice.style.position='absolute';\n");
      out.write("\t\t\t\ttotalprice.style.left = '600px';\n");
      out.write("\t\t\t\ttotalprice.style.top = '50px';\n");
      out.write("\t\t\t    var word = document.createTextNode(e); \t\t\t \t\n");
      out.write("\t\t\t    totalprice.appendChild(word);\t\t\t   \n");
      out.write("\t\t\t    myDiv.appendChild(totalprice);\n");
      out.write("\t\t\t    my_form.appendChild(myDiv); \n");
      out.write("\t\n");
      out.write("\t\t\t    var changeq = document.createElement('P');\n");
      out.write("\t\t\t    changeq.setAttribute(\"id\", mydemo);\n");
      out.write("\t\t\t    changeq.style.position='absolute';\n");
      out.write("\t\t\t    changeq.style.left = '450px';\n");
      out.write("\t\t\t    changeq.style.color = 'red';\n");
      out.write("\t\t\t    changeq.style.fontWeight = \"900\";\n");
      out.write("\t\t\t    changeq.style.top = '10px';\n");
      out.write("\t\t\t    changeq.style.fontSize = \"70%\";\n");
      out.write("\t\t\t    changeq.style.fontFamily  = \"Lucida Sans Unicode,Lucida Grande,sans-serif\";\n");
      out.write("\t\t\t    var word = document.createTextNode(\"Quailty changed\"); \t\t\t \t\n");
      out.write("\t\t\t    changeq.appendChild(word);\t\t\t   \n");
      out.write("\t\t\t    myDiv.appendChild(changeq);\n");
      out.write("\t\t\t    my_form.appendChild(myDiv); \n");
      out.write("\t\t\t    \n");
      out.write("\t\t\t    \n");
      out.write("\n");
      out.write(" \t\t\t    var removebutton = document.createElement('button'); \n");
      out.write("\t\t\t    removebutton.setAttribute(\"id\", myButton);\n");
      out.write("\t\t\t    removebutton.setAttribute(\"name\",myButton);\n");
      out.write("\t\t\t    removebutton.setAttribute(\"value\",myButton);\n");
      out.write("\t    \n");
      out.write("\t\t\t    removebutton.style.position='absolute';\n");
      out.write("\t\t\t    removebutton.style.left = '590px';\n");
      out.write("\t\t\t    removebutton.style.color = 'black';\n");
      out.write("\t\t\t    /* removebutton.style.fontWeight = \"900\"; */\n");
      out.write("\t\t\t    removebutton.style.top = '110px';\n");
      out.write("\t\t\t   /*  removebutton.style.border = \"none\"; */\n");
      out.write("\t\t\t   \tremovebutton.style.backgroundColor=\"white\";\n");
      out.write("\t\t\t    removebutton.style.fontFamily = \"Lucida Sans Unicode,Lucida Grande, sans-serif\";\n");
      out.write("\n");
      out.write("\t\t\t\tvar word  = document.createTextNode(\"Remove item\");\n");
      out.write("\t\t\t\tremovebutton.appendChild(word);\n");
      out.write("\t\t\t\tmyDiv.appendChild(removebutton); \n");
      out.write("\t\t\t\tmy_form.appendChild(myDiv);  \n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("/* \t\t\t\tvar a = document.createElement('a');\n");
      out.write("\t\t\t\tvar linkText = document.createTextNode(\"remove button\");\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\ta.setAttribute(\"id\", myButton);\n");
      out.write("\t\t\t\ta.setAttribute(\"name\",myButton);\n");
      out.write("\t\t\t\ta.setAttribute(\"value\",myButton);\n");
      out.write("\t\t\t\ta.style.position='absolute';\n");
      out.write("\t\t\t\ta.style.left = '780px';\n");
      out.write("\t\t\t\ta.style.color = 'black';\n");
      out.write("\t\t\t\ta.style.fontWeight = \"900\";\n");
      out.write("\t\t\t\ta.style.top = '150px';\n");
      out.write("\t\t\t\ta.title = \"my title text\";\n");
      out.write("\t\t\t\ta.href = \"http://localhost:8080/mainpage/checkout.jsp\";\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\ta.appendChild(linkText);\n");
      out.write("\t\t\t\tmyDiv.appendChild(a);  */\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t    \t\t\t    \n");
      out.write("/* \t\t\t    var s = document.createElement('INPUT'); \n");
      out.write("\t\t\t    s.setAttribute(\"id\", \"submitbotton\");\n");
      out.write("\t\t\t    s.style.position='absolute';\n");
      out.write("\t\t\t    s.style.left = '640px';\n");
      out.write("\t\t\t    s.style.color = 'blue';\n");
      out.write("\t\t\t    s.style.fontWeight = \"900\";\n");
      out.write("\t\t\t    s.style.top = '150px';\n");
      out.write("\t\t\t\ts.setAttribute(\"type\", \"submit\");\n");
      out.write("\t\t\t\ts.setAttribute(\"value\",\"update quality\");\n");
      out.write("\t\t\t\tmyDiv.appendChild(s); \n");
      out.write("\t\t\t\tmy_form.appendChild(myDiv);   */\n");
      out.write("\t\t\t    \n");
      out.write(" \t\t\t    var s = document.createElement('button'); \n");
      out.write("\t\t\t    s.setAttribute(\"id\", udateQ);\n");
      out.write("\t\t\t    s.setAttribute(\"name\",udateQ);\n");
      out.write("\t\t\t    s.setAttribute(\"value\",udateQ);\n");
      out.write("\t    \n");
      out.write("\t\t\t    s.style.position='absolute';\n");
      out.write("\t\t\t    s.style.left = '450px';\n");
      out.write("\t\t\t    s.style.color = 'black';\n");
      out.write("\t\t\t   /*  s.style.fontWeight = \"900\"; */\n");
      out.write("\t\t\t    s.style.top = '110px';\n");
      out.write("\t\t\t    s.style.backgroundColor=\"white\";\n");
      out.write("\t\t\t    s.style.fontFamily = \"Lucida Sans Unicode,Lucida Grande, sans-serif\";\n");
      out.write("\t\t\t   /*  s.style.fontFamily  = \"Lucida Sans Unicode,Lucida Grande,sans-serif\"; */\n");
      out.write("\t\t\t\tvar word  = document.createTextNode(\"update quailty\");\n");
      out.write("\t\t\t\ts.appendChild(word);\n");
      out.write("\t\t\t\tmyDiv.appendChild(s); \n");
      out.write("\t\t\t\tmy_form.appendChild(myDiv);  \n");
      out.write("\t\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t    document.body.appendChild(my_form);\n");
      out.write("\n");
      out.write("\t\t\t\tvar x = document.getElementById(myS).value;\n");
      out.write("\t\t\t   document.getElementById(mydemo).innerHTML = \"Quality: \" + x;    \n");
      out.write(" \t\t\t   \n");
      out.write("  \t\t\t    var s = document.getElementById(myS); \n");
      out.write("\t\t\t    s.addEventListener('change',\n");
      out.write("\t\t\t\t\t   function(){\t\t\t\n");
      out.write("\t\t\t    \t   \n");
      out.write("\t\t\t\t   \t\t \tchoose(myS,mydemo);\t\t\t   \t\t\t\t   \n");
      out.write("\t\t\t   \t\t\t},\n");
      out.write("\t\t\t    false); \n");
      out.write("\t\t\t  \n");
      out.write("\t\t\t\t/* test    */\n");
      out.write("   \t \t\t    var removeit = document.getElementById(myButton); \n");
      out.write("\t\t\t    removeit.addEventListener('onclick',\n");
      out.write("\t\t\t\t\t   function(){\t\t\n");
      out.write("\t\t\t    \t\t\t\n");
      out.write("\t\t\t    \t      document.getElementById(mydemo).innerHTML = \"Hello World\";\n");
      out.write("\t\t\t    \t       \n");
      out.write("\t\t\t    \t \t\t/* removeNode(newdiv);\t\t\t */   \t\t\t\t   \n");
      out.write("\t\t\t   \t\t\t},\n");
      out.write("\t\t\t    false);    \n");
      out.write("\t\t\t    \n");
      out.write("\n");
      out.write("\t\t \t\tvar show = document.getElementById(myButton).value;\t\t \t\t\n");
      out.write("\t\t \t\t\n");
      out.write("\t\t \t\tif(show == \"undefined\"){\n");
      out.write("\t\t \t\t\tdocument.getElementById(\"demo\").innerHTML = \"is undefined\";\n");
      out.write("\t\t \t\t\t");

		 				System.out.println("~~~UPDATE~~~~~");
		 			
      out.write("\n");
      out.write("\t\t \t\t\twindow.open(\"http://localhost:8080/mainpage/checkout.jsp\",\"_self\");\n");
      out.write("\t\t \t\t\t\n");
      out.write("\t\t \t\t}\n");
      out.write("\t\t\t    \n");
      out.write("\t   \n");
      out.write("\t\t\t   /*  return document.getElementById(myButton).value ; */\n");
      out.write("\t\t\t    \n");
      out.write("\t\t\t}  \n");
      out.write("\t\t\t \n");
      out.write("\t\t\t \n");
      out.write("\t\t\t \n");
      out.write("\t\t\t</script>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<script type=\"text/javascript\">\n");
      out.write("\t \t\t\t\t\tfunction choose(sid,pid) {\n");
      out.write("\t \t\t \t\t\t \t\t\t \t\t  \n");
      out.write("\t \t\t\t \t\t\tvar x = document.getElementById(sid).value;\n");
      out.write("\t \t\t\t \t\t\t/* pid.style.fontFamily  = \"Lucida Sans Unicode,Lucida Grande,sans-serif\"; */\n");
      out.write("\t \t\t\t \t\t\tdocument.getElementById(pid).innerHTML = \"Changed! current quality is : \" + x;\n");
      out.write("\t \t\t\t \t\t\t\n");
      out.write("\t \t\t\t \t\t\t\n");
      out.write("\t \t\t\t \t\t\t// update total price \t\n");
      out.write("\t \t\t\t \t\t\n");
      out.write("\t \t\t\t \t\t\t\n");
      out.write("\t \t\t\t \t\t\t\n");
      out.write("\t \t\t\t \t\t}\n");
      out.write("\t \t\t\t\t\t/* var myDiv = [\"divA\",\"divB\",\"divC\",\"divD\",\"divE\"]; */\n");
      out.write("\t \t\t\t\t\tfunction removeNode(removeTarget){\n");
      out.write("\t \t\t\t\t\t\tvar list = document.getElementById(removeTarget);\n");
      out.write("\t \t\t\t\t\t   list.parentNode.removeChild(list); \n");
      out.write("\t \t\t\t\t\t   \n");
      out.write("\t \t\t\t\t\t   \n");
      out.write("\n");
      out.write("\t \t\t\t\t\t}\n");
      out.write("\t \t\t\t\t\t\n");
      out.write("\t\t\t</script>\n");
      out.write("\t\t\t\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\t\t<body>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t");
      out.write("\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t<div class= \"fruitlistCheckOut\">\n");
      out.write("\t\t\t\t<div class = \"logo\"> </div>\n");
      out.write("\t\t\t\t<h3 class = \"fruitTitle\"> Shopping Cart</h3>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t<button id = \"menu\"></button>\t\t\n");
      out.write("\t\t\t\t\t<!-- <div id=\"panel\">Hello world!</div>  -->\n");
      out.write("\t\t  \t\t\t\n");
      out.write("\t  \t\t\t\t<a href= \"http://localhost:8080/mainpage/show_info.jsp\">\n");
      out.write("\t\t\t\t\t<img id = \"FButton\">\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class = \"transparency\">\n");
      out.write("\t\t\t\t\t\t<div class =\"Fword\">fruits </div>\t\n");
      out.write("\t\t\t\t\t</div> \n");
      out.write("\t\t\t\t \t</a>   \n");
      out.write("\t\t\t\t \t\n");
      out.write("\t\t \t\t \t<a href= \"http://localhost:8080/mainpage/account_info.jsp\">\n");
      out.write("\t\t\t\t\t<img id = \"AButton\" > \n");
      out.write("\t\t\t\t\t<div class = \"transparencyAccount\">\n");
      out.write("\t\t\t\t\t\t<div class =\"Aword\">My account </div>\t\n");
      out.write("\t\t\t\t\t</div> \n");
      out.write("\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t \t\n");
      out.write("\t\t\t\t \t<a href= \"http://localhost:8080/mainpage/a1.jsp\">\n");
      out.write("\t\t\t\t\t\t<img class = \"WButton\" > \n");
      out.write("\t\t\t\t\t\t<div class = \"transparencyWelcome\">\n");
      out.write("\t\t\t\t\t\t\t<div class =\"Wword\">Welcome Page </div>\t\n");
      out.write("\t\t\t\t\t\t</div> \n");
      out.write("\t\t\t\t\t</a> \n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<p id=\"demo\"></p>\t\t\t\t\t\n");
      out.write("\t\t\t\t\t");
String userN =(String)session.getAttribute("userName");  
      out.write("\n");
      out.write("\t\t\t\t\t");
 String user =(String)session.getAttribute("userId");  
      out.write("\n");
      out.write("\t\t\t");

				String filePath;
				
				if(user == null){
					filePath = "/Users/Chiaoysbaby/desktop/pro1/mainpage/user1.txt";			
				}
				else{
					StringBuilder originalLine = new StringBuilder();
					originalLine.append("/Users/Chiaoysbaby/desktop/pro1/mainpage/");
					StringBuilder userName = new StringBuilder();
					userName.append(user);
					userName.append(".txt");
					
					originalLine.append(userName);
					System.out.println("store to this path: "+">" +originalLine +"<"    );
					
					String newStr = originalLine.toString();
					filePath = new String(newStr); 

				}
			 	
				
				
				/* String filePath = "/Users/Chiaoysbaby/desktop/pro1/mainpage/user1.txt"; */
				String respberryNum= "";
				String redtomatoNum= "";
				String yellowtomatoNum= "";
				String appleNum= "";
				String pearNum= "";
								
				BufferedReader it = new BufferedReader(new FileReader(filePath));
				HashMap<String, LinkedList<String> > map = new  HashMap<String, LinkedList<String> >();
								
					String line = it.readLine();
	
					while(line != null){
						System.out.println("first read --> " + line);
						int size = line.length();
			
						String unit1 = Character.toString(line.charAt(0));
						String unit2 = Character.toString(line.charAt(1));
	
						if(unit1.equals("r") && unit2.equals("a")  ){
							LinkedList link = new LinkedList();
							respberryNum = line.substring(10,size);	
							String respberryPrice = "3";
							String imagePath = "raspberry.jpg";
							link.add(imagePath);
							link.add(respberryPrice);  // add price of respberry
							link.add(respberryNum);   // add quality 
							int total = Integer.parseInt(respberryPrice) * Integer.parseInt(respberryNum);
							String totalprice = Integer.toString(total);
							link.add(totalprice);
							
							map.put("raspberry",link);
						}
						if(unit1.equals("r") && unit2.equals("e")){
							LinkedList link = new LinkedList();
							String redtomatoPrice = "5";
							String imagePath = "tomatos.jpg";
							redtomatoNum = line.substring(10,size);
							int total = Integer.parseInt(redtomatoPrice)*Integer.parseInt(redtomatoNum);
							String totalPrice  = Integer.toString(total);
							link.add(imagePath); //add image src
							link.add(redtomatoPrice); // add price
							link.add(redtomatoNum); // add quality 
							link.add(totalPrice); // add  total price
							map.put("redtomato",link);
						}
						if(unit1.equals("y")){
							LinkedList link = new LinkedList();
							String yellowtomatoPrice = "5";
							String imagePath = "tomatos.jpg";
	 						yellowtomatoNum = line.substring(13, size);
	 						int a = Integer.parseInt(yellowtomatoPrice);
	 						int b = Integer.parseInt(yellowtomatoNum);
	 	 					int total = a*b;
							String totalPrice  = Integer.toString(total);
							link.add(imagePath); //add image src
							link.add(yellowtomatoPrice); // add price
							link.add(yellowtomatoNum); // add quality 
							link.add(totalPrice); // add  total price							
							map.put("yellowtomato",link); 
						}
						if(unit1.equals("a")){
							LinkedList link = new LinkedList();
							String applePrice = "1";
							String imagePath = "applenew.jpg";
							appleNum = line.substring(6, size);
						 	int a = Integer.parseInt(applePrice);
							int b = Integer.parseInt(appleNum); 
							int total = a*b;							
		 					String totalPrice  = Integer.toString(total);
							link.add(imagePath); //add image src
							link.add(applePrice); // add price
							link.add(appleNum); // add quality 
							link.add(totalPrice); // add  total price	 
													 
							map.put("apple",link);
						}
						if(unit1.equals("p")){
							LinkedList link = new LinkedList();
							String pearPrice = "1";
							String imagePath = "pearsnew.jpg";							
							pearNum  = line.substring(5, size);		
							int a = Integer.parseInt(pearPrice);
							int b = Integer.parseInt(pearNum);
							int total = a*b;
							
							String totalPrice  = Integer.toString(total);
							link.add(imagePath); //add image src
							link.add(pearPrice); // add price
							link.add(pearNum); // add quality 
							link.add(totalPrice); // add  total price								
							map.put("pear",link);  
						}

						line = it.readLine();
					
					}
					
				 
				
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<table class = \"itemtable\">\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<th class = \"Itemth\" > Item  </th>\n");
      out.write("\t\t\t\t\t<th  class = \"therth1\" > Item Price </th> \n");
      out.write("\t\t\t\t\t<th class = \"therth2\" > Quality </th>\n");
      out.write("\t\t\t\t\t<th class = \"therth3\"> Total Price </th>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t \t\t\t\n");
      out.write(" \t\t\t");

				/* store values in  keylist[][] */
				Set set = map.keySet();
			    int mapsize = map.size();
				Iterator current = set.iterator();
				int size = map.size();
				int row = size;
				int col = 5;
				String[][] keylist = new String[size][5];
				
				
				int count = 0;
				int totalPrice = 0; 
				while(current.hasNext()){
					String key = current.next().toString();
					int s = 0;
					keylist[count][s] = key;  // store key  in [][0] 
					s++;
					
 	 				for( int i = 0; i< 4; i++){
						keylist[count][s] = map.get(key).get(i);  
						if(i == 3){
							totalPrice = totalPrice + Integer.parseInt(map.get(key).get(i)) ;							
						}
						s++;					
					}   			
					count ++;
				}
				System.out.println(">>>>  total price: " +totalPrice);
 				StringBuffer values = new StringBuffer();				
				
 				for(int i =0; i<row; i++){
 					 values.append('[');
					for(int j = 0; j< col; j++){
					
						values.append('"').append(keylist[i][j]  ).append('"');
						 if (j<(col-1) ) {
						        values.append(',');
						    }
					}
					
					 values.append(']');
					 if( i<(row-1)){
						 values.append(',');	 
					 }
					 
				} 
				
				System.out.println("value: " +values );   
				/* ((HttpServletResponse)response).sendRedirect("/mainpage/checkout.jsp"); */
			
      out.write("\t \n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class = \"proceedToCheckOut\">\n");
      out.write("\t\t\t\t\t<h3 class = \"proceedStyle\">Order summary: </h3>\n");
      out.write("\t\t\t\t\t<h3 class = \"proceedStyle2\"> Subtotal:  $ ");
      out.print( totalPrice );
      out.write("  </h3> \n");
      out.write("\t\t\t\t\t<h3 class = \"proceedStyle2\"> shipping: TBD  </h3> \t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<form action = \"/mainpage/account_info.jsp\" method = \"POST\" >\n");
      out.write("\t\t\t\t\t\t<!-- <input type = \"submit\" value = \"check out\" name =\"checkout\"  />  -->\n");
      out.write("\t\t\t\t\t\t<input type = \"submit\" value = \"Proceed to checkout\" name =\"proceed\" id = \"proceed\"  /> \n");
      out.write("\t\t\t\t\t</form>\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t <script type=\"text/javascript\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t\tvar i;\n");
      out.write("\t\t\t\t \tvar j;\n");
      out.write("\t\t\t\t \tvar array;\n");
      out.write("\t\t\t\t \tvar x = new Array(");
      out.print(row);
      out.write(");\n");
      out.write("\t\t\t\t \tfor (var i = 0; i < ");
      out.print(row);
      out.write("; i++) {\n");
      out.write("\t\t\t\t \t  x[i] = new Array(");
      out.print(row);
      out.write(");\n");
      out.write("\t\t\t\t \t}\t\t\t \t\t\t\t \t\t\t\n");
      out.write("\t\t\t\t\tx = [");
      out.print( values );
      out.write("];  \n");
      out.write("\t\t\t\t\t \n");
      out.write("\t\t\t\t\tvar topa = '330px';\n");
      out.write("\t\t\t\t\tvar topb = '580px';\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tvar mySelect = [\"mySelectA\",\"mySelectB\", \"mySelectC\", \"mySelectD\",\"mySelectE\"];\n");
      out.write("\t\t\t\t\tvar ChangeQality = [\"QualityA\",\"QualityB\",\"QualityC\", \"QualityD\",\"QualityE\"];\n");
      out.write("\t\t\t\t\tvar toprange = [\"250px\",\"420px\",\"590px\",\"760px\",\"930px\"];\n");
      out.write("\t\t\t\t\tvar myDiv = [\"divA\",\"divB\",\"divC\",\"divD\",\"divE\"];\n");
      out.write("\t\t\t\t\tvar myButton = [\"myButtonA\",\"myButtonB\",\"myButtonC\",\"myButtonD\",\"myButtonE\"];\n");
      out.write("\t\t\t\t\tvar updateQ = [\"updatQualityA\",\"updatQualityB\",\"updatQualityC\",\"updatQualityD\",\"updatQualityE\"];\n");
      out.write("\t\t\t\t\tvar returnvalue;\n");
      out.write("\t\t\t\t\tfor(var count = 0; count < ");
      out.print(row);
      out.write(" ; count ++){\n");
      out.write("\t\t\t\t\t\titemnode2(x[count][0],x[count][1],x[count][2],x[count][3],x[count][4],toprange[count],mySelect[count],ChangeQality[count],myDiv[count],myButton[count],updateQ[count]);  \n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\n");
      out.write("\t\t\t </script>\t\n");
      out.write("\t\t\t \n");
      out.write(" \t\t\t\t");

					
					/* update quality and total price */
					
				 	String[] mySelect = {"mySelectA","mySelectB", "mySelectC", "mySelectD","mySelectE"};
 					String[] myButton = {"myButtonA","myButtonB","myButtonC","myButtonD","myButtonE"};
 					String[] myDiv = {"divA","divB","divC","divD","divE"};
 					String[] myQuality = {"updatQualityA","updatQualityB","updatQualityC","updatQualityD","updatQualityE"};
 					
 					StringBuffer newvalues = new StringBuffer();
 					String[][] newMatrix = new String[row][col];
					String currentfruit = "";
					String  Select = "";
					String Quality = "";
					String Removebutton = ""; 

					int oldrow = row;
					StringBuffer updateValues = new StringBuffer();	
		 			int x = 0;
		 			int newrow = 0;
					for( x =0 ; x< row; x++){ 
						/* System.out.println("select value " +mySelect[0] +" -> "  + Select0 );  */
						
						Removebutton = (String)request.getParameter(myButton[x]); 
						Select = (String)request.getParameter(mySelect[x]);
						Quality = (String)request.getParameter(myQuality[x]);
					
				
						System.out.println("button value " +myButton[x] +" -> "  +Removebutton );	
						System.out.println("Quality value " +myQuality[x] +" -> "  +Quality );	
					
					
						
					/*action: remove items 
					  copy all items except the request item to a temp file, and rename the temp file to the user file
					*/	
					if(Removebutton != null ){

					 
      out.write(" \t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t \t\n");
      out.write(" \t\t\t\t \t\t<p id=\"demo\" style= \"color:blue\"> </p>\n");
      out.write("\t\t\t\t\t\t<!-- rearrange items\t  -->\n");
      out.write("\t\t\t \t\t\t<script type=\"text/javascript\">\t\t\t\t \t\t\t\n");
      out.write("\n");
      out.write("\t\t\t\t \t\t\tfor(var i =0; i< ");
      out.print( row );
      out.write(" ; i++ ){\n");
      out.write("\t\t\t\t \t\t\t\tvar list = document.getElementById(myDiv[i]);\n");
      out.write("\t\t\t\t\t \t\t\tlist.parentNode.removeChild(list);\n");
      out.write("\t\t\t\t \t\t\t}\n");
      out.write("\t\t\t\t\t\t\t \t\t\t\t\t\t\t \n");
      out.write("\t\t\t\t\t\t</script>    \n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t");

 							currentfruit = keylist[x][0];
			 				String  tempfilePath = "/Users/Chiaoysbaby/desktop/pro1/mainpage/temp.txt";
			 				int num = 0;
			 				File currentFile = new File(filePath);
			 				File tempFile = new File(tempfilePath);
			 				tempFile.createNewFile();
		 				
			 				BufferedReader now = new BufferedReader(new FileReader(filePath));	 
			 				FileWriter w = new FileWriter(tempFile,true);
			 				BufferedWriter tempwritebuffer = new BufferedWriter(w);
			 				
			 				String currentline = now.readLine();
			 				System.out.println("if remove ..... " +currentfruit); 
			 				String targeyellowtomato = "yellowtomato";
			 				String targetraspberry = "raspberry";
			 				String targetredtomato = "redtomato";
			 				String targetapple = "apple";
			 				String targetpear = "pear"; 
			 				int rangeOfString = 0;
			 				String target = "";
			 				
			 				if(currentfruit.equals(targetraspberry)){
			 					rangeOfString = 9;
			 					target = targetraspberry;
			 				}
			 				if(currentfruit.equals(targeyellowtomato)){
			 					rangeOfString = 12;
			 					target = targeyellowtomato;
			 				}	
			 				if(currentfruit.equals(targetredtomato)){
			 					rangeOfString = 9;
			 					target = targetredtomato;
			 				}
			 				if(currentfruit.equals(targetapple)){
			 					rangeOfString = 5;
			 					target = targetapple;
			 				}
			 				if(currentfruit.equals(targetpear)){
			 					rangeOfString = 4;
			 					target = targetpear;
			 				}
						
	
			 				if(currentfruit.equals(target)){
			 				
	 		 					while(currentline != null){
	 		 													
	 		 						StringBuilder tempstr = new StringBuilder(); 
									int sizeline = currentline.length();

									if(sizeline >= rangeOfString){ 
										
										if(!currentline.substring(0, rangeOfString).equals(target) ){ 
											tempstr.append(currentline);
											String str = tempstr.toString();
											tempwritebuffer.write(str);												
											tempwritebuffer.newLine(); 												
							 		 	}  
									} 
			 						 else{
										tempstr.append(currentline);
										String str = tempstr.toString();
										tempwritebuffer.write(str);
										tempwritebuffer.newLine();
									} 											 
									currentline = now.readLine();										
								}
			 					tempwritebuffer.flush();
			 					tempwritebuffer.close();		 				
			 					// rename the file 
			 				 	tempFile.renameTo(currentFile); 

								
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t");
 			 				
			 					
			 					int y = 0; 
								int z = 0;
								for(int i =0; i < row; i++){
									z = 0;
								     if(!keylist[i][0].equals(currentfruit)){
								 		 for(int j =0; j<col; j++){									 			
											newMatrix[y][z] = keylist[i][j];  											
											z++;
								 		 } 
								 		y++; 	 
								 	}								 	
								}
								int UpdateTotalPrice = 0;
								for(int i =0; i < y; i++){
								 	for(int j =0; j<col; j++){
								 		System.out.print("----> "+ newMatrix[i][j]);
								 		
								 		if(j == 4){
								 			UpdateTotalPrice = UpdateTotalPrice + Integer.parseInt(newMatrix[i][4]) ;	
								 			System.out.println("  Price "+ newMatrix[i][4]);
								 		}
								 		
								 		/* UpdateTotalPrice = UpdateTotalPrice + Integer.parseInt(newMatrix[i][4]) ;	 */
								 		/* System.out.print("@@@@@current price>>: "+UpdateTotalPrice ); */
								 	}
								 	System.out.println(" ");
								 } 
								
								 newrow = y;	
								
								// store in updatevalue
				 															
				 				for(int i =0; i<newrow; i++){
				 					updateValues.append('[');
									for(int j = 0; j< col; j++){
									
										updateValues.append('"').append(newMatrix[i][j]  ).append('"');
										 if (j<(col-1) ) {
											 updateValues.append(',');
										    }
									}
									
									updateValues.append(']');
									 if( i<(row-1)){
										 updateValues.append(',');	 
									 }									 
								} 
							
								System.out.println("updateValues: " +updateValues ); 
								System.out.println("newrow:" +newrow);  
								System.out.println("Update price: "+UpdateTotalPrice);
								System.out.println("--------------------------------------------------------------");			 	

								
								
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- update the subtotal price after removing items -->\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class = \"proceedToCheckOut\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3 class = \"proceedStyle\">Order summary: </h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3 class = \"proceedStyle2\"> Subtotal:  $ ");
      out.print( UpdateTotalPrice );
      out.write("  </h3> \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3 class = \"proceedStyle2\"> shipping: TBD  </h3> \t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<form action = \"/mainpage/account_info.jsp\" method = \"POST\" >\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type = \"submit\" value = \"Proceed to checkout\" name =\"proceed\" id = \"proceed\"  /> \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</form>\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\t \t\t\t \t\t\t\n");
      out.write("\t\t\t\t\t\t \t\t\tvar i;\n");
      out.write("\t\t\t\t\t\t\t\t \tvar j;\n");
      out.write("\t\t\t\t\t\t\t\t \tvar array;\n");
      out.write("\t\t\t\t\t\t\t\t \tvar x = new Array(");
      out.print(row);
      out.write(");\n");
      out.write("\t\t\t\t\t\t\t\t \tfor (var i = 0; i < ");
      out.print(row);
      out.write("; i++) {\n");
      out.write("\t\t\t\t\t\t\t\t \t  x[i] = new Array(");
      out.print(row);
      out.write(");\n");
      out.write("\t\t\t\t\t\t\t\t \t}\t\t\t \t\t\t\t \t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\tx =  [");
      out.print( updateValues );
      out.write("];\t\n");
      out.write("\t\t\t\t\t\t\t\t\tvar y = ");
      out.print(newrow);
      out.write(";\t\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\tfor(var count = 0; count < ");
      out.print(newrow);
      out.write("; count++ ){\n");
      out.write("\t\t\t\t\t\t\t\t\t\titemnode2(x[count][0],x[count][1],x[count][2],x[count][3],x[count][4],toprange[count],mySelect[count],ChangeQality[count],myDiv[count],myButton[count],updateQ[count]);   \t  \t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t</script>  \n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t \t\t\t\t");
 }
      out.write("\n");
      out.write("\t\t\t \t\t\t \t\t\t\t\t\n");
      out.write("\t\t\t\t\t");
 }
      out.write("\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\n");
      out.write("\t\t\t\t\t");
	
						/* update quality of items and total price */
				 		if(Quality != null){
				 		
						System.out.println("**** select friut " + Select);  
						currentfruit = keylist[x][0];
						System.out.println("current fruit: "+currentfruit );						
										 				
						String strPath;
						
						if(user == null){
							/* default setting: if we don't use data from database */
							strPath = "/Users/Chiaoysbaby/desktop/pro1/mainpage/user1.txt";			
						}
						else{
							
							/* search user info in database */
							StringBuilder originalLine = new StringBuilder();
							originalLine.append("/Users/Chiaoysbaby/desktop/pro1/mainpage/");
							StringBuilder userName = new StringBuilder();
							userName.append(user);
							userName.append(".txt");
							
							originalLine.append(userName);
							System.out.println("store to this path: "+">" +originalLine +"<"    );
							
							String newStr = originalLine.toString();
							strPath = new String(newStr); 

						}
												
						
		 				File strFile = new File(strPath);
			 			if (!strFile.exists()) {
			 					System.out.println("create new txt file for the user");
			 					strFile.createNewFile();
			 				}

						 BufferedWriter objWriter = new BufferedWriter(new FileWriter(strFile , true)); 
														
						 StringBuilder a = new StringBuilder(); 
						 a.append(currentfruit);
						 a.append(" ");
						 a.append(Select);
						 String str = a.toString();
						 objWriter.write(str); 
						 objWriter.newLine();
										 
						 objWriter.flush();
						 objWriter.close();
			  
						/* 	x is the current item: update new quality and total price  */				 			
						keylist[x][3] = Select;
					 	int newtotal = Integer.parseInt(keylist[x][2])*Integer.parseInt(keylist[x][3]);
					 	String newTotalPrice = Integer.toString(newtotal);					 		
					 	keylist[x][4] = newTotalPrice;
					 	
					 	/* update subtotal price in order summary */
					 	int updatePrice = 0;
					 	System.out.println("row: " +x);
					 	for(int i =0; i< row; i++){
					 		for(int j =0; j<5; j++){
					 			System.out.println("----: "+keylist[i][j]);
					 			if(j == 4){
					 				updatePrice = updatePrice + Integer.parseInt(keylist[i][j]); 
					 			}
					 		}
					 	}
					 	
					 						 						 										
			 			for(int i =0; i<row; i++){
			 					newvalues.append('[');
								for(int j = 0; j< col; j++){								
									newvalues.append('"').append(keylist[i][j]  ).append('"');
									 if (j<(col-1) ) {
										 newvalues.append(',');
									    }
								}
								
								newvalues.append(']');
								 if( i<(row-1)){
									 newvalues.append(',');	 
								 }
								 
						} 
			 			System.out.println(">>>value: " +newvalues );  
			 			System.out.println(">>>update Subtotal: " +updatePrice );  
			 			System.out.println("---------------------------------------------");
			 					 				
					
      out.write(" \t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<!-- display the subtotal price after updating quality of items -->\n");
      out.write("\t\t\t\t\t\t\t<div class = \"proceedToCheckOut\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class = \"proceedStyle\">Order summary: </h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class = \"proceedStyle2\"> Subtotal:  $ ");
      out.print( updatePrice );
      out.write("  </h3> \n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class = \"proceedStyle2\"> shipping: TBD  </h3> \t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t<form action = \"/mainpage/account_info.jsp\" method = \"POST\" >\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type = \"submit\" value = \"Proceed to checkout\" name =\"proceed\" id = \"proceed\"  /> \n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\t\t\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t \t\t\t\t\t\t<!-- rearrange items -->\n");
      out.write("\t\t\t\t\t \t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\t\t\t \t\t\t\n");
      out.write("\t\t\t\t \t\t\tvar i;\n");
      out.write("\t\t\t\t\t\t \tvar j;\n");
      out.write("\t\t\t\t\t\t \tvar array;\n");
      out.write("\t\t\t\t\t\t \tvar x = new Array(");
      out.print(row);
      out.write(");\n");
      out.write("\t\t\t\t\t\t \tfor (var i = 0; i < ");
      out.print(row);
      out.write("; i++) {\n");
      out.write("\t\t\t\t\t\t \t  x[i] = new Array(");
      out.print(row);
      out.write(");\n");
      out.write("\t\t\t\t\t\t \t}\t\t\t \t\t\t\t \t\t\t\n");
      out.write("\t\t\t\t\t\t\tx = [");
      out.print( newvalues );
      out.write("];  \t\t\t\t\t \t  \n");
      out.write("\t\t\t\t\t\t\tvar count = ");
      out.print(x);
      out.write(";\n");
      out.write("\t\t\t\t\t\t\t\titemnode2(x[count][0],x[count][1],x[count][2],x[count][3],x[count][4],toprange[count],mySelect[count],ChangeQality[count],myDiv[count],myButton[count],updateQ[count]);  \n");
      out.write("\t\t\t\t\t\t\t</script>  \n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t");
 }
      out.write(" \t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t \t");
}
      out.write("  \n");
      out.write("\t\t \t\t\t\t\t\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\t\t</div>\t\n");
      out.write("\t\n");
      out.write("\t\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
