/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2017-08-09 07:26:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class fruitorder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

 
			
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"mainfruit.css\"> \n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("\t<body>\n");
      out.write("\t<!-- <form action = \"first\" method = \"POST\" > -->\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t<form action = \"/mainpage/fruitorder.jsp\" method = \"POST\" >\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t");
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t");
      out.write("\n");
      out.write("\t\t\t");
      classes.fruitlist obj_checkout = null;
      obj_checkout = (classes.fruitlist) _jspx_page_context.getAttribute("obj_checkout", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (obj_checkout == null){
        obj_checkout = new classes.fruitlist();
        _jspx_page_context.setAttribute("obj_checkout", obj_checkout, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
        out.write("\n");
        out.write("\t\t\t");
        org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("obj_checkout"), request);
        out.write("\n");
        out.write("\t\t\t");
      }
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class = \"fruitButton\">\n");
      out.write("\t\t\t\t<a href= \"http://localhost:8080/mainpage/fruitorder.jsp\">\n");
      out.write("\t\t\t\t<!-- <img class = \"fruitButtonGo\" alt=\"I am fruit button\" >  -->\n");
      out.write("\t\t\t\t<img class = \"fruitButtonGo\" > \n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t\tfruits\n");
      out.write("\t\t\t</div> \n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class = \"accountButton\" >\n");
      out.write("\t\t\t\t<a href= \"http://localhost:8080/mainpage/account.jsp \">\n");
      out.write("\t\t\t\t<img class = \"accountButtonGo\" > \n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t\tMy account\n");
      out.write("\t\t\t</div>  \n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\n");
      out.write("\t\t\t<div class= \"fruitlist\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t<h3 class = \"fruitTitle\"> These are our current fruits, click the picture to get information of fruits.</h3>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t\t\t <!-- <a href=\"http://localhost:8080/mainpage/tomato.jsp\">  -->\n");
      out.write("\t\t\t\t <form action = \"tomato.jsp\" method = \"POST\" >\n");
      out.write("\t\t\t\t <input class = \"tomato\" type=\"submit\" name=\"tomato\" value = \"tomato\"  >\n");
      out.write("\t\t\t\t<!--  </a> -->\n");
      out.write("\t\t\t\t</form>\t\t\t\t\t\t\t\t\t\t \t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t<input class = \"raspberry\" type=\"submit\" name=\"raspberry\" value = \"raspberry\"  >\n");
      out.write("\t\t\t\t<input class = \"pear\" type=\"submit\" name=\"pear\" value = \"pear\"  >\n");
      out.write("\t\t\t\t<input class = \"apple\" type=\"submit\" name=\"apple\" value = \"apple\"  >\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t");
 
 						if(obj_checkout.submitbutton() == true){
 							String aa = obj_checkout.getcheckoutt();
 							System.out.println("-----> go to check out");
 							System.out.println("-----> " +aa);
 							String red = obj_checkout.getredtomato();
 							String yel = obj_checkout.getyellowtomato();
 							if(!red.equals("")){
 								System.out.println("-----> " +red);
 							}
 							if(!yel.equals("")){
 								System.out.println("-----> " +yel);
 							} 
 									
 					
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t\t\t\t\t");
      if (true) {
        _jspx_page_context.forward("checkout.jsp");
        return;
      }
      out.write(" \n");
      out.write("\t\t\t\t\t");
  
						} 
					 
      out.write("\t\n");
      out.write("\t\t\t\t\t \n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t\t \n");
      out.write("\t\t \t\t\t ");
  HashMap<String, Integer> map = obj_checkout.myshoppingbag();
					 	 Set set = map.entrySet();	
					 //Set set = obj_checkout.myshoppingbag.entrySet();
						 Iterator box = set.iterator();
					 
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class = \"rightsidetomato\" >\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t");
  String toStr = request.getParameter("tomato");  
      out.write("\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t");
  if (toStr != null){  
      out.write("  \n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<h2 class =\"shopBagTitle\"> Details in tomato: </h2>\n");
      out.write("\t\t\t\t\t\t\t<p class  = \"tomatoDetail\" > Our Cherry Tomatoes are from Northwest Oregon. Oregon \n");
      out.write("\t\t\t\t\t\t\thas moderate temperatures, it is a great place for cherry tomato to grow. Our tastes \n");
      out.write("\t\t\t\t\t\t\t juicy and sweet. We recommend to make it as salads or roasted foods.        \n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\n");
      out.write("\t\t\t\t\t\t\t<p> Each box has 4 pounds of cherry tomatoes. We provide red and yellow cherry tomatoes.\n");
      out.write("\t\t\t\t\t\t\t\tPlease select how many boxes you want. \t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t\tRed cherry tomatoes :  <br>\n");
      out.write("\t\t\t\t\t\t\t<select name=\"redtomato\" size=\"1\"  value = '");
      out.print( obj_checkout.getredtomato() );
      out.write("'>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"0\">0</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">1</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">2</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"3\">3</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"4\">4</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"5\">5</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"6\">6</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"7\">7</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"8\">8</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"9\">9</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"10\">10</option>\n");
      out.write("\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t <br>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\tYellow cherry tomatoes : <br>\n");
      out.write("\t\t\t\t\t\t\t<select name=\"yellowtomato\" size=\"1\"  value = '");
      out.print( obj_checkout.getyellowtomato() );
      out.write("' >\n");
      out.write("\t\t\t\t\t\t\t<option value=\"0\">0</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">1</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">2</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"3\">3</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"4\">4</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"5\">5</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"6\">6</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"7\">7</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"8\">8</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"9\">9</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"10\">10</option>\n");
      out.write("\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class = \"rightsideraspberry\" >\n");
      out.write("\t\t\t\t\t\t");
 
						String rasStr = request.getParameter("raspberry"); 
						if(rasStr != null){
						
      out.write("\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<h2 class =\"shopBagTitle\"> Details in Raspberry: </h2>\n");
      out.write("\t\t\t\t\t\t\t<p class  = \"tomatoDetail\" > Our raspberries are from Salem, Albany, Beavercreek and Hillsboro.The raspberry \n");
      out.write("\t\t\t\t\t\t\treasons in Oregon are from June to September. Because of great water sources and temperatures in Oregon, \n");
      out.write("\t\t\t\t\t\t\t we are proud of our fruits. Our raspberry tastes sweet and less sour. We recommend to eat our fresh\n");
      out.write("\t\t\t\t\t\t\t raspberry directly, or make it as yogurt or pies. \n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t\traspberry:  <br>\n");
      out.write("\t\t\t\t\t\t\t<select name=raspberry size=\"1\"  value = '");
      out.print( obj_checkout.getraspberry() );
      out.write("'  >\n");
      out.write("\t\t\t\t\t\t\t<option value=\"0\">0</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">1</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">2</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"3\">3</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"4\">4</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"5\">5</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"6\">6</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"7\">7</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"8\">8</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"9\">9</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"10\">10</option>\n");
      out.write("\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t");
 								
						}
						
      out.write(" \n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t");
 
					String pearStr = request.getParameter("pear"); 
					if(pearStr != null){
						out.print("--> : "+pearStr); 	
					}
					
      out.write(" \n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t");
 
					String appStr = request.getParameter("apple"); 
					if(appStr != null){
						out.print("--> : "+appStr); 	
					}
					
      out.write(" \n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class = \"checkout\">\n");
      out.write("\t\t\t\t\t\t<input type = \"submit\" value = \"add to shopping bag\" name =\"shoppingbag\"  /> \n");
      out.write("\t\t\t\t\t\t<input type = \"submit\" value = \"check out\" name =\"checkout\"  /> \n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</form>\n");
      out.write("\t\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
