/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2017-08-02 11:01:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class newaccount_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

 
				
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\"> \n");
      out.write("<title>customer info</title>\n");
      out.write("</head>\n");
      out.write("\t<body>\n");
      out.write("\t\t<form action = \"first\" method = \"POST\" >\n");
      out.write("\t\t<div class= \"account\">\n");
      out.write("\t\t\t<h3> Hi, dear our new customer, please provide your information to us </h3>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t \tFirst name: <input type=\"text\" name=\"fname\"><br>\n");
      out.write("\t\t\t\tLast name: <input type=\"text\" name=\"lname\"><br>\n");
      out.write("\t\t\t\tPassword: <input tyle = \"password\" name= \"password\"> <br>\n");
      out.write("\t\t\t\tEmail: <input type=\"text\" name=\"email\"><br>\n");
      out.write("\t\t\t\tMobile number: <input type=\"text\" name=\"mobno\"><br>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t");
      out.write("\n");
      out.write("\t\t\t\t");
      classes.action obj_phone = null;
      obj_phone = (classes.action) _jspx_page_context.getAttribute("obj_phone", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (obj_phone == null){
        obj_phone = new classes.action();
        _jspx_page_context.setAttribute("obj_phone", obj_phone, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
        out.write("\n");
        out.write("\t\t\t\t");
        org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("obj_phone"), request);
        out.write("\n");
        out.write("\t\t\t\t");
      }
      out.write("\n");
      out.write("\t\t\t\t<p>Got message....</p>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<p>Student Last Name: \n");
      out.write("        \t\t ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((classes.action)_jspx_page_context.findAttribute("obj_phone")).getmobno())));
      out.write("\n");
      out.write("      \t\t\t</p>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t");
  
					boolean aa	 = obj_phone.validate();
					out.println("bool  " + aa);
				
				
      out.write(" \n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t\t");
 String data = "myDataAsString";
				   String value=request.getParameter("mobno");
				session.setAttribute("myData", data );
      out.write(" \n");
      out.write("\t\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t\t");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Address: <textarea rows=\"5\" cols=\"5\" name=\"address\"></textarea><br> -->\n");
      out.write("\t\t\t\tAddress: <input type=\"text\" name=\"address\"> \n");
      out.write("\t\t\t\tCity: <input type=\"text\" name=\"city\">\n");
      out.write("\t\t\t\t<!-- State: <input type=\"text\" name=\"state\"><br> -->\n");
      out.write("\t\t\t\tState: <select name=\"state\" size=\"1\">\n");
      out.write("\t\t\t\t<option selected value=\"\">State...</option>\n");
      out.write("\t\t\t\t<option value=\"None\">None</option>\n");
      out.write("\t\t\t\t<option value=\"\">-- UNITED STATES --</option>\n");
      out.write("\t\t\t\t<option value=\"Alabama\">Alabama</option>\n");
      out.write("\t\t\t\t<option value=\"Alaska\">Alaska</option>\n");
      out.write("\t\t\t\t<option value=\"Arizona\">Arizona</option>\n");
      out.write("\t\t\t\t<option value=\"Arkansas\">Arkansas</option>\n");
      out.write("\t\t\t\t<option value=\"California\">California</option>\n");
      out.write("\t\t\t\t<option value=\"Colorado\">Colorado</option>\n");
      out.write("\t\t\t\t<option value=\"Connecticut\">Connecticut</option>\n");
      out.write("\t\t\t\t<option value=\"Delaware\">Delaware</option>\n");
      out.write("\t\t\t\t<option value=\"Florida\">Florida</option>\n");
      out.write("\t\t\t\t<option value=\"Georgia\">Georgia</option>\n");
      out.write("\t\t\t\t<option value=\"Hawaii\">Hawaii</option>\n");
      out.write("\t\t\t\t<option value=\"Idaho\">Idaho</option>\n");
      out.write("\t\t\t\t<option value=\"Illinois\">Illinois</option>\n");
      out.write("\t\t\t\t<option value=\"Indiana\">Indiana</option>\n");
      out.write("\t\t\t\t<option value=\"Iowa\">Iowa</option>\n");
      out.write("\t\t\t\t<option value=\"Kansas\">Kansas</option>\n");
      out.write("\t\t\t\t<option value=\"Kentucky\">Kentucky</option>\n");
      out.write("\t\t\t\t<option value=\"Louisiana\">Louisiana</option>\n");
      out.write("\t\t\t\t<option value=\"Maine\">Maine</option>\n");
      out.write("\t\t\t\t<option value=\"Maryland\">Maryland</option>\n");
      out.write("\t\t\t\t<option value=\"Massachusetts\">Massachusetts</option>\n");
      out.write("\t\t\t\t<option value=\"Michigan\">Michigan</option>\n");
      out.write("\t\t\t\t<option value=\"Minnesota\">Minnesota</option>\n");
      out.write("\t\t\t\t<option value=\"Mississippi\">Mississippi</option>\n");
      out.write("\t\t\t\t<option value=\"Missouri\">Missouri</option>\n");
      out.write("\t\t\t\t<option value=\"Montana\">Montana</option>\n");
      out.write("\t\t\t\t<option value=\"Nebraska\">Nebraska</option>\n");
      out.write("\t\t\t\t<option value=\"Nevada\">Nevada</option>\n");
      out.write("\t\t\t\t<option value=\"New Hampshire\">New Hampshire</option>\n");
      out.write("\t\t\t\t<option value=\"New Jersey\">New Jersey</option>\n");
      out.write("\t\t\t\t<option value=\"New Mexico\">New Mexico</option>\n");
      out.write("\t\t\t\t<option value=\"New York\">New York</option>\n");
      out.write("\t\t\t\t<option value=\"North Carolina\">North Carolina</option>\n");
      out.write("\t\t\t\t<option value=\"North Dakota\">North Dakota</option>\n");
      out.write("\t\t\t\t<option value=\"Ohio\">Ohio</option>\n");
      out.write("\t\t\t\t<option value=\"Oklahoma\">Oklahoma</option>\n");
      out.write("\t\t\t\t<option value=\"Oregon\">Oregon</option>\n");
      out.write("\t\t\t\t<option value=\"Pennsylvania\">Pennsylvania</option>\n");
      out.write("\t\t\t\t<option value=\"Rhode Island\">Rhode Island</option>\n");
      out.write("\t\t\t\t<option value=\"South Carolina\">South Carolina</option>\n");
      out.write("\t\t\t\t<option value=\"South Dakota\">South Dakota</option>\n");
      out.write("\t\t\t\t<option value=\"Tennessee\">Tennessee</option>\n");
      out.write("\t\t\t\t<option value=\"Texas\">Texas</option>\n");
      out.write("\t\t\t\t<option value=\"Utah\">Utah</option>\n");
      out.write("\t\t\t\t<option value=\"Vermont\">Vermont</option>\n");
      out.write("\t\t\t\t<option value=\"Virginia\">Virginia</option>\n");
      out.write("\t\t\t\t<option value=\"Washington\">Washington</option>\n");
      out.write("\t\t\t\t<option value=\"West Virginia\">West Virginia</option>\n");
      out.write("\t\t\t\t<option value=\"Wisconsin\">Wisconsin</option>\n");
      out.write("\t\t\t\t<option value=\"Wyoming\">Wyoming</option>\n");
      out.write("\t\t\t\t<option value=\"\">-- CANADA --</option>\n");
      out.write("\t\t\t\t<option value=\"Alberta\">Alberta</option>\n");
      out.write("\t\t\t\t<option value=\"British Columbia\">British Columbia</option>\n");
      out.write("\t\t\t\t<option value=\"Manitoba\">Manitoba</option>\n");
      out.write("\t\t\t\t<option value=\"New Brunswick\">New Brunswick</option>\n");
      out.write("\t\t\t\t<option value=\"Newfoundland and Labrador\">Newfoundland and Labrador</option>\n");
      out.write("\t\t\t\t<option value=\"Northwest Territories\">Northwest Territories</option>\n");
      out.write("\t\t\t\t<option value=\"Nova Scotia\">Nova Scotia</option>\n");
      out.write("\t\t\t\t<option value=\"Nunavut\">Nunavut</option>\n");
      out.write("\t\t\t\t<option value=\"Ontario\">Ontario</option>\n");
      out.write("\t\t\t\t<option value=\"Prince Edward Island\">Prince Edward Island</option>\n");
      out.write("\t\t\t\t<option value=\"Quebec\">Quebec</option>\n");
      out.write("\t\t\t\t<option value=\"Saskatchewan\">Saskatchewan</option>\n");
      out.write("\t\t\t\t<option value=\"Yukon Territory\">Yukon Territory</option>\n");
      out.write("\t\t\t\t<option value=\"\">-- AUSTRALIA --</option>\n");
      out.write("\t\t\t\t<option value=\"Australian Capital Territory\">Australian Capital Territory</option>\n");
      out.write("\t\t\t\t<option value=\"New South Wales\">New South Wales</option>\n");
      out.write("\t\t\t\t<option value=\"Northern Territory\">Northern Territory</option>\n");
      out.write("\t\t\t\t<option value=\"Queensland\">Queensland</option>\n");
      out.write("\t\t\t\t<option value=\"South Australia\">South Australia</option>\n");
      out.write("\t\t\t\t<option value=\"Tasmania\">Tasmania</option>\n");
      out.write("\t\t\t\t<option value=\"Victoria\">Victoria</option>\n");
      out.write("\t\t\t\t<option value=\"Western Australia\">Western Australia</option>\n");
      out.write("\t\t\t\t</select>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t<input type = \"submit\" value = \"create a new account\" name =\"submit\"  /> \n");
      out.write("\t\t\t\t<input type = \"submit\" value = \"show databases\" name =\"show databases\"  /> \n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t</form>\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
