/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2017-11-20 14:58:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.File;
import java.io.Writer;
import java.io.BufferedWriter;
import java.io.FileWriter;

public final class pear_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

 
			
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"mainfruit.css\"> \n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("<title>pear</title>\n");
      out.write("<script> \n");
      out.write("$(document).ready(function(){\n");
      out.write("    $(\"#menu\").click(function(){\n");
      out.write("       /*  $(\"#panel\").toggle(10);  */\n");
      out.write("\t\t$(\".transparency\").toggle(10);  \n");
      out.write("        $(\".transparencyAccount\").toggle(20);\n");
      out.write("        $(\".transparencyWelcome\").toggle(30); \n");
      out.write("    });\n");
      out.write("\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\t<body>\n");
      out.write("\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t");
      out.write("\n");
      out.write("\t\t\t");
      classes.fruitlist obj_checkout = null;
      obj_checkout = (classes.fruitlist) _jspx_page_context.getAttribute("obj_checkout", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (obj_checkout == null){
        obj_checkout = new classes.fruitlist();
        _jspx_page_context.setAttribute("obj_checkout", obj_checkout, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
        out.write("\n");
        out.write("\t\t\t");
        org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("obj_checkout"), request);
        out.write("\n");
        out.write("\t\t\t");
      }
      out.write("\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t<div class= \"fruitlist\">\n");
      out.write("\t\t\t\t\t<div class = \"logo\">\n");
      out.write("\t\t\t\t\t</div>\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<h3 class = \"fruitTitle\">Fruits</h3>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<button id = \"menu\"></button>\t\t\n");
      out.write("\t\t\t\t\t<!-- <div id=\"panel\">Hello world!</div>  -->\n");
      out.write("\t\t  \t\t\t\n");
      out.write("\t  \t\t\t\t<a href= \"http://localhost:8080/mainpage/show_info.jsp\">\n");
      out.write("\t\t\t\t\t<img id = \"FButton\">\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class = \"transparency\">\n");
      out.write("\t\t\t\t\t\t<div class =\"Fword\">fruits </div>\t\n");
      out.write("\t\t\t\t\t</div> \n");
      out.write("\t\t\t\t \t</a>   \n");
      out.write("\t\t\t\t \t\n");
      out.write("\t\t \t\t \t<a href= \"http://localhost:8080/mainpage/account_info.jsp\">\n");
      out.write("\t\t\t\t\t<img id = \"AButton\" > \n");
      out.write("\t\t\t\t\t<div class = \"transparencyAccount\">\n");
      out.write("\t\t\t\t\t\t<div class =\"Aword\">My account </div>\t\n");
      out.write("\t\t\t\t\t</div> \n");
      out.write("\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t \t\n");
      out.write("\t\t\t\t \t<a href= \"http://localhost:8080/mainpage/a1.jsp\">\n");
      out.write("\t\t\t\t\t\t<img class = \"WButton\" > \n");
      out.write("\t\t\t\t\t\t<div class = \"transparencyWelcome\">\n");
      out.write("\t\t\t\t\t\t\t<div class =\"Wword\">Welcome Page </div>\t\n");
      out.write("\t\t\t\t\t\t</div> \n");
      out.write("\t\t\t\t\t</a> \n");
      out.write("\t\t\t\t \t\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t<!-- \t<h2 class = \"fruitTitle\"> These are our current fruits, click the picture to get information of fruits.</h2> -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t");
 String user =(String)session.getAttribute("userId");  
      out.write("\n");
      out.write("\t\t\t\t\t");
String userN =(String)session.getAttribute("userName");  
      out.write("\n");
      out.write("\t\t\t\t\t<div class = \"welcomeword\">\n");
      out.write("\t\t\t\t\t\t\t<p> Hi, ");
out.println( userN); 
      out.write(" <br>\n");
      out.write("\t\t\t\t\t\t\t Welcome black </p> \n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t\t\t<form action = \"/mainpage/tomato.jsp\" method = \"POST\" >\n");
      out.write("\t\t\t\t\t\t<input class = \"tomato\" type=\"submit\" name=\"tomato\" value = \"Tomato\"  >\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<form action = \"/mainpage/raspberry.jsp\" method = \"POST\" >\n");
      out.write("\t\t\t\t\t\t<input class = \"raspberry\" type=\"submit\" name=\"raspberry\" value = \"raspberry\"  >\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<form action = \"/mainpage/pear.jsp\" method = \"POST\" >\n");
      out.write("\t\t\t\t\t\t<input class = \"pear\" type=\"submit\" name=\"pear\" value = \"pear\"  >\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<form action = \"/mainpage/apple.jsp\" method = \"POST\" >\n");
      out.write("\t\t\t\t\t\t<input class = \"apple\" type=\"submit\" name=\"apple\" value = \"apple\"  >\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t");
 
 			if(obj_checkout.submitbutton() == true){
 					String aa = obj_checkout.getcheckoutt();
 					System.out.println("-----> go to check out");
 					System.out.println("-----> " +aa);
 									
 			
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t\t\t\t");
      if (true) {
        _jspx_page_context.forward("checkout.jsp");
        return;
      }
      out.write(" \n");
      out.write("\t\t\t");
  
			} 
			
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class = \"rightside\" >\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t\t<h2 class =\"shopBagTitle\"> Details in Pear: </h2>\n");
      out.write("\t\t\t\t\t<p class  = \"tomatoDetail\" > Our pears are from areas of Rogue River Valley and along the Columbia River near Mt. Hood. \n");
      out.write("\t\t\t\t\tthe warm temperatures in summer seasons in Oregon helps pears plump and juicy. Pear has great nutrition, one pear provides 24% of the recommended daily.\n");
      out.write("\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t<div class = \"checkout\">\n");
      out.write("\t\t\t\t\t\t<form action = \"/mainpage/pear.jsp\" method = \"POST\" >\n");
      out.write("\t\t\t\t\t\t\t<div class = \"pearPrice\">\n");
      out.write("\t\t\t\t\t\t\tEach one $: 1   <br>\n");
      out.write("\t\t\t\t\t\t\tQuality:\n");
      out.write("\t\t\t\t\t\t\t<select name=pear size=\"1\"  value = '");
      out.print( obj_checkout.getpear() );
      out.write("'  >\n");
      out.write("\t\t\t\t\t\t\t<option value=\"0\">0</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">1</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">2</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"3\">3</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"4\">4</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"5\">5</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"6\">6</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"7\">7</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"8\">8</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"9\">9</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"10\">10</option>\n");
      out.write("\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t");
 String pear =obj_checkout.getpear();  
      out.write("\t\n");
      out.write("\t\t\t\t\t\t");

						if(!pear.equals("") && !pear.equals("0") && !pear.equals("pear")){
							System.out.println("**** pear " + pear); 

							String strPath;
							
							if(user == null){
								strPath = "/Users/Chiaoysbaby/desktop/pro1/mainpage/user1.txt";			
							}
							else{
								StringBuilder originalLine = new StringBuilder();
								originalLine.append("/Users/Chiaoysbaby/desktop/pro1/mainpage/");
								StringBuilder userName = new StringBuilder();
								userName.append(user);
								userName.append(".txt");
								
								originalLine.append(userName);
								System.out.println("store to this path: "+">" +originalLine +"<"    );
								
								String newStr = originalLine.toString();
								strPath = new String(newStr); 

							}
						 			
	 						 
	 						File strFile = new File(strPath);
		 					if (!strFile.exists()) {
		 							System.out.println("create new txt file for the user");
		 							strFile.createNewFile();
		 						}
							/*  boolean fileCreated = strFile.createNewFile(); */
							/*  Writer objWriter = new BufferedWriter(new FileWriter(strFile , true));  */
							 BufferedWriter objWriter = new BufferedWriter(new FileWriter(strFile , true)); 
													
							 StringBuilder a = new StringBuilder(); 
							 a.append("pear");
							 a.append(" ");
							 a.append(pear);
							 String str = a.toString();
							 objWriter.write(str); 
							 objWriter.newLine();
		
							 
							 objWriter.flush();
							 objWriter.close();
						 
						}
						
						
      out.write("\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</div> \n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- display how many items  -->\n");
      out.write("\t\t\t\t\t\t<!-- retrieve quality of items in shopping cart from makeMatrix page\t -->\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<button id = \"cartInFruit\"></button>\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "makeMatrix.jsp", out, false);
      out.write("  \n");
      out.write("\t\t\t\t\t\t");
 	
						int NumItem = 0;
						int row = 0;
						String myMatrix =(String)session.getAttribute("itMatrix");
						System.out.println("Matrix: " +myMatrix );   	
						
						String Strrow =(String)session.getAttribute("row");
						System.out.println("how many different fruits?  " +Strrow );   	
										
						if(!Strrow.equals("0")){					
							 row = Integer.parseInt(Strrow);					
						}
						
						if(Integer.parseInt(Strrow)== 0){
						
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<p class= \"countItemsInFruit\"></p>\n");
      out.write("\t\t\t\t\t\t");
 
							NumItem = 0;
						}					
						else{
							NumItem = (Integer)session.getAttribute("NumberOfItem"); 
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<p class= \"countItemsInFruit\">");
      out.print(NumItem);
      out.write("</p>\n");
      out.write("\t\t\t\t\t\t");
 
						}						 			
						
      out.write("\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<input type = \"submit\" value = \"add to shopping cart\" name =\"shoppingbag\" id = \"pearAddButton\"  /> \n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<form action = \"/mainpage/checkout.jsp\" method = \"POST\" >\n");
      out.write("\t\t\t\t\t\t<input type = \"submit\" value = \"check out\" name =\"checkout\"  id = \"pearCheckOutButton\"   /> \n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t</div>\t\t\n");
      out.write("\t\t\t</div>\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
