/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2017-11-20 17:13:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.File;
import java.io.Writer;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.util.Iterator;
import java.util.ListIterator;
import java.util.ArrayList;
import java.util.List;
import java.util.Arrays;

public final class processEdit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

 
				
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"mainfruit.css\"> \n");
      out.write("<title>Insert title here</title>\n");
      out.write("\t \t\t <script type=\"text/javascript\">\n");
      out.write(" \t\t\n");
      out.write("\t\t\t function createtable(x,row){ \n");
      out.write("\t\t\t\t \n");
      out.write("\t\t\t\tvar table = document.createElement('table');\n");
      out.write("\t\t\t\ttable.className=\"tableelement\";\n");
      out.write("\n");
      out.write("\t\t\t\tvar tr = document.createElement('tr');  \n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tvar td1 = document.createElement('td');\n");
      out.write("\t\t\t\tvar words1 = document.createTextNode(\"Item\");\n");
      out.write("\t\t\t\ttd1.setAttribute(\"colspan\", 2);\n");
      out.write("\t\t\t\ttd1.style.color = 'rgb(102, 93, 82)';\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\tvar td2 = document.createElement('td');\n");
      out.write("\t\t\t\ttd2.style.color = 'rgb(102, 93, 82)';\n");
      out.write("\t\t\t\tvar words2 = document.createTextNode(\"Price\");\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tvar td3 = document.createElement('td');\n");
      out.write("\t\t\t\ttd3.style.color = 'rgb(102, 93, 82)';\n");
      out.write("\t\t\t\tvar words3 = document.createTextNode(\"Quality\");\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tvar td4 = document.createElement('td');\n");
      out.write("\t\t\t\ttd4.style.color = 'rgb(102, 93, 82)'\n");
      out.write("\t\t\t\tvar words4 = document.createTextNode(\"Total price\");\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\ttd1.appendChild(words1);\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\ttd2.appendChild(words2);\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\ttd3.appendChild(words3);\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\ttd4.appendChild(words4);\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\ttr.appendChild(td1);\n");
      out.write("\t\t\t\ttr.appendChild(td2);\n");
      out.write("\t\t\t\ttr.appendChild(td3);\n");
      out.write("\t\t\t\ttr.appendChild(td4);\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\ttable.appendChild(tr);\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t  for (var i = 0; i < row; i++){\n");
      out.write("\t\t\t\t\t var j =0;\t\t\t\t\t\t\t \n");
      out.write("\t\t\t\t\t var tr = document.createElement('tr');   \n");
      out.write("\t\t\t\t\t \n");
      out.write("\t\t\t\t\t      var td1 = document.createElement('img');\n");
      out.write("\t\t\t\t\t      td1.src = x[i][j+1];\n");
      out.write("\t\t\t\t\t      td1.style.width = '80%'; \n");
      out.write("\t\t\t\t\t      \n");
      out.write("\t\t\t\t\t      var td2 = document.createElement('td');\n");
      out.write("\t\t\t\t\t      td2.style.width = '40%';\n");
      out.write("\t\t\t\t\t     \t\t      \n");
      out.write("\t\t\t\t\t      var td3 = document.createElement('td');\t\t\t\t\t    \n");
      out.write("\t\t\t\t\t      td3.style.width = '15%';\n");
      out.write("\t\t\t\t\t      \t\t\t\t\t     \n");
      out.write("\t\t\t\t\t      var td4 = document.createElement('td');\n");
      out.write("\t\t\t\t\t      td4.style.width = '15%';\n");
      out.write("\n");
      out.write("\t\t\t\t\t      var td5 = document.createElement('td');\n");
      out.write("\t\t\t\t\t      td5.style.width = '20%';\n");
      out.write("\t\n");
      out.write("\t\t\t\t\t      var text2 = document.createTextNode(x[i][j]);\n");
      out.write("\t\t\t\t\t      var text3 = document.createTextNode(x[i][j+2]);\t\t\t\t\t      \t\t\t\t\t      \t\t\t\t\t      \n");
      out.write("\t\t\t\t\t      var text4 = document.createTextNode(x[i][j+3]);\n");
      out.write("\t\t\t\t\t      var text5 = document.createTextNode(x[i][j+4]);\n");
      out.write("\n");
      out.write("\t\t\t\t\t      td2.appendChild(text2);\n");
      out.write("\t\t\t\t\t      td3.appendChild(text3);\n");
      out.write("\t\t\t\t\t      td4.appendChild(text4);\n");
      out.write("\t\t\t\t\t      td5.appendChild(text5);\n");
      out.write("\n");
      out.write("\t\t\t\t      tr.appendChild(td1);\n");
      out.write("\t\t\t\t      tr.appendChild(td2);\n");
      out.write("\t\t\t\t \t  tr.appendChild(td3); \n");
      out.write("\t\t    \t\t  tr.appendChild(td4);\n");
      out.write("\t\t\t\t\t  tr.appendChild(td5);\n");
      out.write("\n");
      out.write("\t\t\t\t      table.appendChild(tr);\n");
      out.write("\t\t\t\t  }\n");
      out.write("\t\t\t\t  \n");
      out.write("\t\t\t\t  \n");
      out.write("\t\t\t\t  document.body.appendChild(table);\n");
      out.write("\t\t\t\t  \n");
      out.write("\n");
      out.write("\t\t\t} \n");
      out.write("\n");
      out.write("\t\t\t</script> \n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\t<body>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t \n");
      out.write("\t\t\t\t");
      out.write("\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t");
      classes.action updateObj = null;
      updateObj = (classes.action) _jspx_page_context.getAttribute("updateObj", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (updateObj == null){
        updateObj = new classes.action();
        _jspx_page_context.setAttribute("updateObj", updateObj, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
        out.write("\n");
        out.write("\t\t\t\t");
        org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("updateObj"), request);
        out.write("\n");
        out.write("\t\t\t\t");
      }
      out.write("\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("<!-- \t<form action=\"processEdit.jsp#thisDiv\" method=post>\t\t -->\t\t\t \n");
      out.write(" \t\t\t\t\n");
      out.write(" \t\t\t\t");
 if(updateObj.validate() == true){ 
      out.write("\t\t \t\t\t\n");
      out.write("\t\t\t\t\t\t\t");
      if (true) {
        _jspx_page_context.forward("first");
        return;
      }
      out.write(" \t\t\t\t\t \n");
      out.write("\t\t\t\t");
 } 
      out.write(" \n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("<!-- \t\t\t\t<div class = \"fruitButtoncheck\">\n");
      out.write("\t\t\t\t\t<a href= \"http://localhost:8080/mainpage/show_info.jsp\">\n");
      out.write("\t\t\t\t\t<img class = \"fruitButtonGo\"  > \n");
      out.write("\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\tfruits\n");
      out.write("\t\t\t\t</div> \n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t<div class = \"accountButton\" >\n");
      out.write("\t\t\t\t\t<a href= \"http://localhost:8080/mainpage/account_info.jsp \">\n");
      out.write("\t\t\t\t\t<img class = \"accountButtonGo\"  > \n");
      out.write("\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\tMy account\n");
      out.write("\t\t\t\t</div>  -->\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div class= \"fruitlistacount\">\n");
      out.write("\t\t\t\t<h3 class = \"fruitTitle\"> My account </h3>\n");
      out.write("\t\t\t\t\n");
      out.write(" \t\t\t\t\t<button id = \"menu\"></button>\t\n");
      out.write(" \t\t\t\t\t<div class = \"logo\"> </div>\t\n");
      out.write("\t\t  \t\t\t\n");
      out.write("\t  \t\t\t\t<a href= \"http://localhost:8080/mainpage/show_info.jsp\">\n");
      out.write("\t\t\t\t\t<img id = \"FButton\">\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class = \"transparency\">\n");
      out.write("\t\t\t\t\t\t<div class =\"Fword\">fruits </div>\t\n");
      out.write("\t\t\t\t\t</div> \n");
      out.write("\t\t\t\t \t</a>   \n");
      out.write("\t\t\t\t \t\n");
      out.write("\t\t \t\t \t<a href= \"http://localhost:8080/mainpage/account_info.jsp\">\n");
      out.write("\t\t\t\t\t<img id = \"AButton\" > \n");
      out.write("\t\t\t\t\t<div class = \"transparencyAccount\">\n");
      out.write("\t\t\t\t\t\t<div class =\"Aword\">My account </div>\t\n");
      out.write("\t\t\t\t\t</div> \n");
      out.write("\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t \t\n");
      out.write("\t\t\t\t \t<a href= \"http://localhost:8080/mainpage/a1.jsp\">\n");
      out.write("\t\t\t\t\t\t<img class = \"WButton\" > \n");
      out.write("\t\t\t\t\t\t<div class = \"transparencyWelcome\">\n");
      out.write("\t\t\t\t\t\t\t<div class =\"Wword\">Welcome Page </div>\t\n");
      out.write("\t\t\t\t\t\t</div> \n");
      out.write("\t\t\t\t\t</a>  \n");
      out.write("\t\t\t\t\n");
      out.write("<form action=\"processEdit.jsp#thisDiv\" method=post>\t\t\t\t\t\t\n");
      out.write("\t\t\t\t<p id=\"demo\"></p>\t\n");
      out.write(" \t\t\t\t\n");
      out.write("\t\t\t\t");
String userN =(String)session.getAttribute("userName");  
      out.write("\n");
      out.write("\t\t\t\t");
 String user =(String)session.getAttribute("userId");  
      out.write("\n");
      out.write("\t\t\t\t");
 String addState =(String)session.getAttribute("AddressState");  
      out.write("\n");
      out.write("\t\t\t\t\t");
      out.write("\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t");
 
				  StringBuilder temp = new StringBuilder();
				  temp.append(user);
				  temp.append(".txt");
				  String userFilePath = temp.toString();
				  
				  List<String> textFiles = new ArrayList<String>();
				  File dir = new File("/Users/Chiaoysbaby/desktop/pro1/mainpage");
				  for (File file : dir.listFiles()) {
				    if (file.getName().endsWith((userFilePath))) {
				      textFiles.add(file.getName());
				    }
				  }
				  ListIterator<String> listIterator = null;
				 
				  listIterator = textFiles.listIterator();
				  StringBuffer yesfile=  new StringBuffer();
				  
				  while(listIterator.hasNext()){
			           /*  System.out.println(listIterator.next()); */
			            yesfile.append(listIterator.next());
			        }
				  String userFile = yesfile.toString();
				  System.out.println("found file ------>" +userFile );
				  
				
      out.write(" \n");
      out.write("\t\n");
      out.write("\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "makeMatrix.jsp", out, false);
      out.write("  \n");
      out.write("\t\t\t\n");
      out.write(" \t\t\t\t");
 
				
					int row = 0;
					String myMatrix =(String)session.getAttribute("itMatrix");
					System.out.println("values in account_info: " +myMatrix );   	
					
					String Strrow =(String)session.getAttribute("row");
					System.out.println("how many different fruits?  " +Strrow );   	
					
					if(!Strrow.equals("0")){
					
						 row = Integer.parseInt(Strrow);					
					}
				
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t <script type=\"text/javascript\">\t\t\t\n");
      out.write("\t\t\t\t\tvar i;\n");
      out.write("\t\t\t\t \tvar j;\n");
      out.write("\t\t\t\t \tvar array;\n");
      out.write("\n");
      out.write("\t\t\t\t \tvar x = new Array(");
      out.print(row);
      out.write(");\n");
      out.write("\t\t\t\t \tvar i;\n");
      out.write("\t\t\t\t \tfor (i = 0; i < ");
      out.print(row);
      out.write("; i++) {\n");
      out.write("\t\t\t\t \t  x[i] = new Array(");
      out.print(row);
      out.write(");\n");
      out.write("\t\t\t\t \t}\t\n");
      out.write("\t\t\t\t \t\n");
      out.write("\t\t\t\t \tif( i!= 0){\n");
      out.write("\t\t\t\t\t\tx = [");
      out.print( myMatrix );
      out.write("];  \t\t\t\t\t\n");
      out.write("\t\t\t\t\t\tcreatetable(x,");
      out.print(row);
      out.write(");\n");
      out.write("\t\t\t\t \t}\n");
      out.write("\t\t\t\t</script>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t");

						int maxR = Integer.parseInt(Strrow);
					
      out.write("\n");
      out.write("\t   \t   \t\t\t<div class = \"account_info_welcomeword\">\n");
      out.write("\t\t\t\t\t\t\t<p> Hi, <b> ");
out.println( userN); 
      out.write("</b>, this is your order history. </p>\t\t\n");
      out.write("\t\t\t\t\t\t\t<span>\n");
      out.write("\t\t\t\t\t\t\t");
if (maxR ==0){ 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<p style = \"text-align:center\" >  <b > No order history.</b> </p>\n");
      out.write("\t\t\t\t\t\t\t");
} 
      out.write("\t\t\n");
      out.write("\t\t\t\t\t\t\t</span>\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t\t");

					
						System.out.println("how many row? " + Strrow);
						int maxRow = Integer.parseInt(Strrow);
						int beginningLocation = 400;
						int beginningLocationP = 400;
						
						
						if(maxRow == 0){
							beginningLocation = 300;
							beginningLocationP = 250;
						}
						else{
							System.out.println("maxRow: " + maxRow);
							for(int i =0; i <= maxRow; i++ ){
								/* System.out.println("maxRow: " + maxRow); */
				/* 				if(maxRow >=3){
									System.out.println("3333");
									beginningLocation = beginningLocation + 40;
									beginningLocationP = beginningLocationP + 25; 
								}
								else{
									System.out.println("2222");
									beginningLocation = beginningLocation + 30;
									beginningLocationP = beginningLocationP + 5; 
								} */
								if(maxRow == 4){
									System.out.println("maxRow == 4 ");
									/* beginningLocation = beginningLocation + (i* 1); */
									beginningLocationP = (beginningLocation -50);
									i++;
								}
								if(maxRow == 3){
									System.out.println("maxRow == 3 ");
									beginningLocation = beginningLocation + (i* 70);
									beginningLocationP =(beginningLocation -50);
									i++;
								}else{
									System.out.println("else:  " +maxRow );
									beginningLocation = beginningLocation + (i* 55);
									beginningLocationP =(beginningLocation -50);
									i++;									
								}
								

								
							}
						}
						
						StringBuilder divLocation = new StringBuilder();
						String tempStr = Integer.toString(beginningLocation);
						//white box location
						divLocation.append("'");
						divLocation.append(tempStr);
						divLocation.append("px");
						divLocation.append("'");
						
						StringBuilder PLocation = new StringBuilder();
						String PStr = Integer.toString(beginningLocationP);
						// word location
						PLocation.append("'");
						PLocation.append(PStr);
						PLocation.append("px");
						PLocation.append("'");
						
						System.out.println("word location >>> " +PLocation );
						System.out.println("white box location >>> " +divLocation );
						String newPLoc = PLocation.toString(); 
						String newDivLoc = divLocation.toString(); 
					
      out.write("\n");
      out.write("\t\t\t\t\t\n");
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t\t\t\t<div id = \"thisP\"> \n");
      out.write("\t\t\t\t\t\t<p > The is your account information. </p>\n");
      out.write("\t\t\t\t\t</div>\t\n");
      out.write("\t\t\t\t\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t \t\t\t\t\tvar a = document.getElementById(\"thisP\");\n");
      out.write("\t\t\t\t\t\t\ta.style.position='absolute';\n");
      out.write("\t\t\t\t\t\t\ta.style.top = ");
      out.print( newPLoc );
      out.write(";\n");
      out.write("\t\t\t\t\t\t\ta.style.left = '30px'; \n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\n");
      out.write("\t\t\t\t\t\t</script>\n");
      out.write("\t\t\t\t<div  id = \"thisDiv\"  >\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\t\t\t    var a = document.getElementById(\"thisDiv\");\n");
      out.write("\t\t\t\t\t\ta.style.position='absolute';\n");
      out.write("\t\t\t\t\t\ta.style.top = ");
      out.print( newDivLoc );
      out.write(";\n");
      out.write("\t\t\t\t\t\ta.style.left = '30px'; \n");
      out.write("\t\t\t\t\t\t/* a.style.borderBottom = '2px solid rgb(91, 92, 94)'; */\n");
      out.write("\t\t\t\t\t\ta.style.textAlign = 'left';\n");
      out.write("\t\t\t\t\t\ta.style.fontWeight =  'bold';\n");
      out.write("\t\t\t\t\t\ta.style.padding =  '12px';\n");
      out.write("\t\t\t\t\t\t/* a.style.border = '1px solid black';   */\n");
      out.write("\t\t\t\t\t\ta.style.color = 'black';\n");
      out.write("\t\t\t\t\t\ta.style.fontSize = '130%';\n");
      out.write("\t\t\t\t\t\ta.style.width = '75%';\n");
      out.write("\t\t\t\t\t\ta.style.background  = 'white';\n");
      out.write("\t\t\t\t\t\ta.style.opacity = '0.8';\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t \n");
      out.write("\t\t\t\t\t</script>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t\t\t");
 
				String UserId =(String)session.getAttribute("userId");
					System.out.println("UserId: " + UserId);
				
      out.write("\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t");
 String State =(String)session.getAttribute("AddressState");  
      out.write("\n");
      out.write("\t\t\t\t<div  style = \" text-align: right;\">\n");
      out.write("\t\t\t\t<input  class = \"AaveButton\"  type = \"submit\" value = \"Save\" name =\"UpdateUserInfo\"  /> \n");
      out.write("\t\t\t \t<input type=\"hidden\" value = \"");
      out.print(UserId );
      out.write("\" name =\"userID\" >\n");
      out.write("\t\t\t\t</div>\t\t\n");
      out.write("\t\t\t\t\t <table >\n");
      out.write("\t\t\t\t\t  <tr style = \" padding:5px;\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t      \t<td  style = \" padding:5px; width:110px\"  ><b> First Name </b></td>\n");
      out.write("\t\t\t\t\t\t    \t<td  style = \" padding:5px; width:100px\" > <input type=\"text\" name=\"fname\" value = '");
      out.print( updateObj.getfname() );
      out.write("'  ></td>\n");
      out.write(" \t\t\t\t\t\t     \t<span >\n");
      out.write("\t\t\t\t\t\t\t\t");
	String fname_digits =updateObj.getFirstNameError();  
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t");
	if(!fname_digits.equals("")){  
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td  style = \" padding:5px;  color:red; font-size:80%; width:400px\" > ");
      out.print( updateObj.getFirstNameError() );
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t");
} 
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t</span> \n");
      out.write("\t\t\t\t\t  </tr style = \" padding:5px;\">\n");
      out.write(" \t \t\t\t\t   <tr style = \" padding:5px;\">\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<td style = \" padding:5px; width:110px\" ><b> Last Name</b></th>\n");
      out.write("\t\t\t\t\t\t    \t<td style = \" padding:5px; width:100px\" >  <input type=\"text\" name=\"lname\" value = '");
      out.print( updateObj.getlname() );
      out.write("' ></td>\n");
      out.write("\t\t\t\t\t\t\t\t<span >\n");
      out.write("\t\t\t\t\t\t\t\t");
	String lname_digits =updateObj.getLastNameError();  
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t");
	if(!lname_digits.equals("")){ 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td  style = \" padding:5px;  color:red; font-size:80%; width:400px\" > ");
      out.print( updateObj.getLastNameError() );
      out.write(" </td>\n");
      out.write("\t\t\t\t\t\t\t\t");
	} 
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t  </tr style = \" padding:5px;\">\n");
      out.write("\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t   <tr style = \" padding:5px;\">\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<td style = \" padding:5px; width:110px\" ><b> Password</b></th>\n");
      out.write("\t\t\t\t\t\t    \t<td style = \" padding:5px; width:100px\" >  <input type=\"password\" name=\"password\" value = '");
      out.print( updateObj.getpassword() );
      out.write("' ></td>\n");
      out.write("\t\t\t\t\t\t\t\t<span >\n");
      out.write("\t\t\t\t\t\t\t\t");
	String password_digits =updateObj.getPasswordError();   
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t");
	if(!password_digits.equals("")){ 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td  style = \" padding:5px;  color:red; font-size:80%; width:400px\" > ");
      out.print( updateObj.getPasswordError() );
      out.write(" </td>\n");
      out.write("\t\t\t\t\t\t\t\t");
	} 
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t  </tr style = \" padding:5px;\">\n");
      out.write("\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t  \n");
      out.write("\t\t\t\t   <tr style = \" padding:5px;\">\n");
      out.write("\t\t\t\t\t  \t\t\t<td style =  \" padding:5px; width:200px\" ><b> Phone Number</b></td>\n");
      out.write("\t\t\t\t\t\t\t    <td style = \" padding:5px;width:100px\"> <input type=\"text\" name=\"mobno\"value = '");
      out.print(updateObj.getmobno() );
      out.write("' ></td>\n");
      out.write("\t\t\t\t\t  \t\t\t<span class = \"remainderInEdit\">\n");
      out.write("\t\t\t\t\t\t\t\t\t");
String Pres =updateObj.getPhoneError();  
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 if(!Pres.equals("")){  
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td  style = \" padding:5px; color:red; font-size:80%; width:400px\" > ");
      out.print( updateObj.getPhoneError());
      out.write(" </td>\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t</span>\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t </t style = \" padding:5px;\"r>\n");
      out.write("\t\t\t\t     <tr style = \" padding:5px;\">\n");
      out.write("\t\t\t\t\t  \t\t\t<td style =  \"padding:5px; width:110px\" ><b> Email</b></td>\n");
      out.write("\t\t\t\t\t\t\t    <td style = \"padding:5px; width:150px \"> <input type=\"text\" name=\"email\"  value = '");
      out.print( updateObj.getemail() );
      out.write("' ></td>\n");
      out.write("\t\t\t\t\t  \t\t\t<span class = \"remainderInEdit\">\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 String email_digits = updateObj.getEmailError(); 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 if(!Pres.equals("")){  
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style = \" padding:5px; color:red; font-size:80%; width:400px\"> ");
      out.print( updateObj.getEmailError() );
      out.write(" </td>\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t</span>\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t </tr style = \" padding:5px;\">\n");
      out.write("\t\t\t\t\t \n");
      out.write("\t\t\t\t\t <tr style = \" padding:5px;\">\n");
      out.write("\t\t\t\t\t \t\t\t<td style =  \" padding:5px; width:110px\"><b> Address</b></td>\t\n");
      out.write("\t\t\t\t\t \t\t\t<td style =  \" padding:5px; width:110px\"> <input type=\"text\" name=\"address\"  value = '");
      out.print( updateObj.getaddress() );
      out.write("'></td>\n");
      out.write("\t\t\t\t\t\t    \t<td style =  \"  padding:5px; width:110px\"> <input type=\"text\" name=\"city\" value = '");
      out.print( updateObj.getcity() );
      out.write("'  ></td>\n");
      out.write("\t\t\t\t\t\t   \t\t<td style =  \"  padding:5px; width:110px\"> State: <select id =\"state\" name=\"state\" size=\"1\">\n");
      out.write("\t\t\t\t\t\t   \t\t\t\t\t\t\t<option value=\"Alabama\">Alabama</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Alaska\">Alaska</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Arizona\">Arizona</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Arkansas\">Arkansas</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"California\">California</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Colorado\">Colorado</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Connecticut\">Connecticut</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Delaware\">Delaware</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Florida\">Florida</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Georgia\">Georgia</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Hawaii\">Hawaii</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Idaho\">Idaho</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Illinois\">Illinois</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Indiana\">Indiana</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Iowa\">Iowa</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Kansas\">Kansas</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Kentucky\">Kentucky</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Louisiana\">Louisiana</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Maine\">Maine</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Maryland\">Maryland</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Massachusetts\">Massachusetts</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Michigan\">Michigan</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Minnesota\">Minnesota</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Mississippi\">Mississippi</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Missouri\">Missoquri</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Montana\">Montana</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Nebraska\">Nebraska</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Nevada\">Nevada</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"New Hampshire\">New Hampshire</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"New Jersey\">New Jersey</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"New Mexico\">New Mexico</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"New York\">New York</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"North Carolina\">North Carolina</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"North Dakota\">North Dakota</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Ohio\">Ohio</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Oklahoma\">Oklahoma</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Oregon\">Oregon</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Pennsylvania\">Pennsylvania</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Rhode Island\">Rhode Island</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"South Carolina\">South Carolina</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"South Dakota\">South Dakota</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Tennessee\">Tennessee</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Texas\">Texas</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Utah\">Utah</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Vermont\">Vermont</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Virginia\">Virginia</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Washington\">Washington</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"West Virginia\">West Virginia</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Wisconsin\">Wisconsin</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Wyoming\">Wyoming</option>\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</select>\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");

													
											        String[] states = {"California", "Alabama", "Arkansas", "Arizona", "Alaska", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming" };

											        // State names in alphabetical order

											        Arrays.sort(states);
											        int index = 0; 
													int sizeofState = states.length;
											        for(int i =0; i <sizeofState; i++ ){
											        //	System.out.println("-> "+states[i] );
											        	if(states[i].equals(addState)){
											        		index = i;
											        	}
											        }
											        
											        String idx = Integer.toString(index);
											       // System.out.println("-----> index " + idx);
													
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
 String aa = "5"; 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tvar str = ");
      out.print(idx);
      out.write(";\n");
      out.write("\t\t\t");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  var element = document.getElementById('state');\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t ");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  /*  element.selectedIndex = se;  */\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t   element.selectedIndex = str;  \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  /* element.selectedIndex = \"2\";  */\n");
      out.write("\t\t\t\t\t   \t\t\t\t\t\t\t   \t\n");
      out.write("\t\t\t\t\t   \t\t\t\t\t\t\t   \t/* \telement.setAttribute(\"value\", \"West Virginia\"); */\n");
      out.write("\t\t\t\t\t   \t\t\t\t\t\t\t\t \n");
      out.write("\t\t\t\t\t \t\t\t\t\t\t\t\t</script>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t   \t\t\n");
      out.write("\t\t\t\t\t\t   \t\t</td style = \" padding:5px;\">\n");
      out.write("\t\t\t\t\t\t   \t\t <tr style = \" padding:5px;\">\n");
      out.write("\t\t\t\t\t\t   \t\t<span >\n");
      out.write("\t\t\t\t\t\t\t\t");
String add =updateObj.getAddressError();  
      out.write(" \n");
      out.write("\t\t\t\t\t\t\t\t");
if(!add.equals("")){  
      out.write(" \n");
      out.write("\t\t\t\t\t\t\t\t\t<td  colspan=\"3\" style = \" padding:5px; color:red; font-size:80%; width:400px\"> ");
      out.print( updateObj.getAddressError() );
      out.write(" </td>\n");
      out.write("\t\t\t\t\t\t\t\t");
}
      out.write(" \t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t\t </tr style = \" padding:5px;\">\n");
      out.write("\t\t\t \t\t\t\t\t <tr style = \" padding:5px;\">\n");
      out.write("\t\t\t\t\t\t\t\t<span>\n");
      out.write("\t\t\t\t\t\t\t\t");
String add2 =updateObj.getCityError();  
      out.write(" \n");
      out.write("\t\t\t\t\t\t\t\t");
if(!add2.equals("")){  
      out.write(" \n");
      out.write("\t\t\t\t\t\t\t\t\t<td  colspan=\"3\" style = \" padding:5px; color:red; font-size:80%; width:400px\"> ");
      out.print( updateObj.getCityError() );
      out.write(" </td>\n");
      out.write("\t\t\t\t\t\t\t\t");
}
      out.write(" \t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t</span>\t\t\t\t\t\t   \t\t\n");
      out.write("\t\t\t\t\t\t   \t\t </tr style = \" padding:5px;\" > \n");
      out.write("\t\t\t\t\t  </tr>\n");
      out.write("\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t  \n");
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t</table>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t \t");

					 	System.out.println("------>got state " + addState);
					 	
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t</div>\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t<form>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
